/* curriculo.js — EL CATÁLOGO DE TEMAS DEL CURSO (4º ESO, rama tecnológica, Madrid).

   Sacado de los saberes básicos oficiales: RD 217/2022 (enseñanzas mínimas) y
   Decreto 65/2022 de la Comunidad de Madrid. No existe API ni fichero abierto con
   esto —está en los decretos—, así que se mantiene aquí a mano.

   PARA QUÉ SIRVE: pedir un tema sin explicar nada. Basta con decir el id
   —«haz fyq-atomo»— y de aquí sale el título, el saber básico del que viene, los
   contenidos que entran y los talleres que hay que escribir. El cómo está en ESTANDAR.md.

   En letras e idiomas los «generadores» no son de números: son de transformar frases,
   analizar oraciones, rellenar huecos o clasificar. El motor es el mismo.            */

/* trimestre: 1, 2 o 3. Orientativo, según programaciones habituales; se ajusta
   cuando Novak traiga la suya. */
const CURRICULO = {

  /* ══════════════ MATEMÁTICAS B (académicas) ══════════════ */
  "Matemáticas B": [
    { id:"mat-b-reales", trimestre:1, bloque:"A. Sentido numérico", titulo:"Números reales e intervalos",
      saber:"Los conjuntos numéricos: relaciones y propiedades. Orden en la recta. Intervalos.",
      entra:["Naturales, enteros, racionales, irracionales y reales","Decimales exactos y periódicos","Fracción generatriz","Intervalos y semirrectas","Valor absoluto","Aproximación y cota de error"],
      generadores:["clasificarNumero","fraccionGeneratriz","intervalos","errorAbsolutoRelativo"] },
    { id:"mates-radicales", trimestre:1, bloque:"A. Sentido numérico", titulo:"Radicales",
      saber:"Operaciones con números reales. Propiedades y relaciones inversas.",
      entra:["Raíz n-ésima y existencia","Exponente fraccionario","Simplificar, sacar y meter factores","Operar","Racionalizar","Radicales con letras","Ecuaciones con radicales"],
      generadores:["simplificar","sumar","multiplicar","racionalizar","conjugado","comparar","potencias","problema"] },
    { id:"mat-b-potencias", trimestre:1, bloque:"A. Sentido numérico", titulo:"Potencias y notación científica",
      saber:"Expresión de cantidades mediante números reales con la precisión requerida.",
      entra:["Propiedades de las potencias","Exponente negativo y cero","Notación científica","Operar en notación científica","Orden de magnitud"],
      generadores:["propiedadesPotencias","aNotacionCientifica","operarNotacion","ordenMagnitud"] },
    { id:"mat-b-proporcionalidad", trimestre:3, bloque:"A. Sentido numérico", titulo:"Porcentajes e interés compuesto",
      saber:"Situaciones de proporcionalidad directa e inversa en diferentes contextos.",
      entra:["Índice de variación","Aumentos y descuentos encadenados","Porcentaje inverso","Interés simple y compuesto","Repartos proporcionales"],
      generadores:["porcentajeDirecto","porcentajeInverso","encadenados","interesCompuesto","reparto"] },
    { id:"mat-b-logaritmos", trimestre:1, bloque:"A. Sentido numérico", titulo:"Logaritmos",
      saber:"Logaritmo de un número: definición y propiedades. Relación con las potencias.",
      entra:["Qué es un logaritmo: la potencia al revés","Logaritmo decimal y neperiano","Propiedades: producto, cociente y potencia","Cambio de base","Ecuaciones exponenciales","Dónde se usan: pH, decibelios, terremotos"],
      generadores:["calcularLog","propiedadesLog","ecuacionExponencial","aplicacionLog"] },
    { id:"mat-b-polinomios", trimestre:1, bloque:"D. Sentido algebraico", titulo:"Polinomios y factorización",
      saber:"Formas equivalentes de expresiones algebraicas.",
      entra:["Operaciones con polinomios","Ruffini y teorema del resto","Raíces","Factorizar","Fracciones algebraicas"],
      generadores:["ruffini","factorizar","raicesPolinomio","simplificarFraccion"] },
    { id:"mat-b-ecuaciones", trimestre:2, bloque:"D. Sentido algebraico", titulo:"Ecuaciones de segundo grado y otras",
      saber:"Estrategias de búsqueda de soluciones en ecuaciones lineales y no lineales.",
      entra:["Fórmula y discriminante","Incompletas","Bicuadradas","Con radicales","Con fracciones","Problemas"],
      generadores:["segundoGrado","bicuadrada","conRadicales","conFracciones","problemaEcuacion"] },
    { id:"mates-sistemas", trimestre:2, bloque:"D. Sentido algebraico", titulo:"Sistemas de ecuaciones",
      saber:"Resolución de sistemas lineales y no lineales sencillos.",
      entra:["Sustitución, igualación y reducción","Interpretación gráfica","Compatible e incompatible","No lineales","Problemas"],
      generadores:["sistemaLineal","sistemaNoLineal","clasificarSistema","problemaSistema"] },
    { id:"mat-b-inecuaciones", trimestre:2, bloque:"D. Sentido algebraico", titulo:"Inecuaciones",
      saber:"Ecuaciones, sistemas e inecuaciones: resolución.",
      entra:["De primer grado","El signo al multiplicar por negativo","De segundo grado","Solución en intervalos","Sistemas de inecuaciones"],
      generadores:["inecuacionLineal","inecuacionCuadratica","sistemaInecuaciones"] },
    { id:"mates-funcion-cuadratica", trimestre:2, bloque:"D. Sentido algebraico", titulo:"La función cuadrática",
      saber:"Relaciones lineales y no lineales: representaciones y propiedades.",
      entra:["Forma general y vértice","Cortes con los ejes","Dibujar la parábola","Máximos y mínimos"],
      generadores:["verticeParabola","cortesEjes","problemaOptimizacion"] },
    { id:"mat-b-funciones", trimestre:3, bloque:"D. Sentido algebraico", titulo:"Funciones: tipos y propiedades",
      saber:"Representación de funciones: interpretación de sus propiedades.",
      entra:["Dominio y recorrido","Continuidad, crecimiento y extremos","Lineal, cuadrática, inversa, radical","Exponencial y logarítmica","Definidas a trozos","Tasa de variación media"],
      generadores:["dominio","tasaVariacion","identificarFuncion","funcionTrozos"] },
    { id:"mat-b-trigonometria", trimestre:3, bloque:"B. Sentido de la medida", titulo:"Trigonometría",
      saber:"Razones trigonométricas de un ángulo agudo y sus relaciones.",
      entra:["Seno, coseno y tangente","Relación fundamental","Razones de 30º, 45º y 60º","Resolver triángulos rectángulos","Alturas y distancias"],
      generadores:["razonTrigonometrica","resolverTriangulo","relacionFundamental","problemaAltura"] },
    { id:"mat-b-geometria-analitica", trimestre:3, bloque:"C. Sentido espacial", titulo:"Geometría analítica",
      saber:"Expresiones algebraicas de una recta.",
      entra:["Vectores: componentes y módulo","Punto medio y distancia","Ecuaciones de la recta","Pendiente","Paralelas y perpendiculares","Posición relativa"],
      generadores:["vectores","distanciaPuntos","ecuacionRecta","posicionRectas"] },
    { id:"mat-b-semejanza", trimestre:3, bloque:"C. Sentido espacial", titulo:"Semejanza y Tales",
      saber:"Propiedades geométricas de objetos matemáticos y de la vida cotidiana.",
      entra:["Teorema de Tales","Criterios de semejanza","Razón en áreas y volúmenes","Escalas","Pitágoras en el espacio"],
      generadores:["tales","razonSemejanza","escalas","pitagoras"] },
    { id:"mat-b-estadistica", trimestre:3, bloque:"E. Sentido estocástico", titulo:"Estadística de dos variables",
      saber:"Variable bidimensional. Tablas de contingencia. Regresión lineal.",
      entra:["Media, mediana, moda y cuartiles","Desviación típica","Diagrama de dispersión","Correlación","Recta de regresión"],
      generadores:["medidasCentralizacion","desviacionTipica","correlacion","prediccionRegresion"] },
    { id:"mat-b-probabilidad", trimestre:3, bloque:"E. Sentido estocástico", titulo:"Probabilidad",
      saber:"Regla de Laplace en experimentos simples y compuestos.",
      entra:["Regla de Laplace","Unión, intersección y contrario","Condicionada","Diagramas de árbol","Con y sin reemplazamiento"],
      generadores:["laplace","sucesos","condicionada","arbol"] },
  ],

  /* ══════════════ FÍSICA Y QUÍMICA ══════════════ */
  "Física y Química": [
    { id:"fyq-cinematica", trimestre:1, bloque:"Movimiento", titulo:"Cinemática",
      saber:"Descripción del movimiento: MRU y MRUA.",
      entra:["Sistema de referencia y trayectoria","MRU: ecuación y gráficas","MRUA: ecuaciones","Caída libre y lanzamiento","Leer gráficas x-t y v-t","Movimiento circular"],
      generadores:["mru","mrua","caidaLibre","leerGrafica","circular"] },
    { id:"fyq-dinamica", trimestre:3, bloque:"Fuerzas", titulo:"Dinámica y leyes de Newton",
      saber:"Las fuerzas como causa de los cambios de movimiento.",
      entra:["Las tres leyes de Newton","Peso, normal y rozamiento","Diagramas de fuerzas","Plano inclinado","Ley de Hooke","Gravitación universal"],
      generadores:["segundaLey","rozamiento","planoInclinado","hooke","gravitacion"] },
    { id:"fyq-energia", trimestre:3, bloque:"Energía", titulo:"Trabajo, energía y potencia",
      saber:"Transferencias de energía: trabajo y calor.",
      entra:["Energía cinética y potencial","Trabajo y potencia","Conservación de la energía mecánica","Rendimiento","Energía y sociedad"],
      generadores:["energiaMecanica","trabajoPotencia","conservacion","rendimiento"] },
    { id:"fyq-calor", trimestre:3, bloque:"Energía", titulo:"Calor y temperatura",
      saber:"El calor como transferencia de energía.",
      entra:["Calor y temperatura no son lo mismo","Calor específico","Cambios de estado y calor latente","Equilibrio térmico","Dilatación"],
      generadores:["calorEspecifico","calorLatente","equilibrioTermico"] },
    { id:"fyq-atomo", trimestre:1, bloque:"Materia", titulo:"Estructura atómica y sistema periódico",
      saber:"Modelos atómicos y organización de los elementos.",
      entra:["Modelos de Thomson, Rutherford y Bohr","Número atómico y másico","Isótopos","Configuración electrónica","Grupos y periodos","Propiedades periódicas"],
      generadores:["particulasAtomo","configuracion","isotopos","ubicarTablaPeriodica"] },
    { id:"fyq-enlace", trimestre:1, bloque:"Materia", titulo:"El enlace químico",
      saber:"Enlaces iónico, covalente y metálico.",
      entra:["Regla del octeto","Enlace iónico","Enlace covalente y estructuras de Lewis","Enlace metálico","Propiedades según el enlace","Fuerzas intermoleculares"],
      generadores:["tipoEnlace","lewis","propiedadesSegunEnlace"] },
    { id:"fyq-formulacion-inorganica", trimestre:1, bloque:"Química", titulo:"Formulación inorgánica",
      saber:"Nomenclatura de compuestos inorgánicos (IUPAC).",
      entra:["Números de oxidación","Óxidos","Hidruros y ácidos hidrácidos","Hidróxidos","Ácidos oxácidos","Sales"],
      generadores:["formulaANombre","nombreAFormula","numeroOxidacion"] },
    { id:"fyq-carbono", trimestre:2, bloque:"Química", titulo:"Química del carbono",
      saber:"Compuestos del carbono y su importancia.",
      entra:["Por qué el carbono es especial","Hidrocarburos: alcanos, alquenos, alquinos","Grupos funcionales","Formular y nombrar","Isomería","Polímeros"],
      generadores:["nombrarOrganico","formularOrganico","identificarGrupo","isomeros"] },
    { id:"fyq-reacciones", trimestre:2, bloque:"Química", titulo:"Reacciones y estequiometría",
      saber:"Cálculos estequiométricos en reacciones químicas.",
      entra:["Ajustar ecuaciones","Mol y masa molar","Cálculos masa-masa","Volúmenes de gases","Reactivo limitante","Rendimiento y pureza"],
      generadores:["ajustar","molMasa","estequiometria","reactivoLimitante","rendimientoPureza"] },
    { id:"fyq-disoluciones", trimestre:2, bloque:"Química", titulo:"Disoluciones y ácidos-base",
      saber:"Concentración de disoluciones. Reacciones ácido-base.",
      entra:["Concentración: g/L, % y molaridad","Diluciones","Ácidos y bases: Arrhenius","Escala de pH","Neutralización","Lluvia ácida"],
      generadores:["molaridad","dilucion","pH","neutralizacion"] },
  ],

  /* ══════════════ LENGUA CASTELLANA Y LITERATURA ══════════════ */
  "Lengua Castellana y Literatura": [
    { id:"len-oracion-simple", trimestre:1, bloque:"Reflexión sobre la lengua", titulo:"Análisis sintáctico: la oración simple",
      saber:"Relaciones sintácticas: sujeto y predicado, complementos.",
      entra:["Sujeto y predicado","Complemento directo e indirecto","Circunstanciales","Atributo y predicativo","Suplemento y agente","Oraciones impersonales"],
      generadores:["identificarSujeto","identificarComplemento","analizarOracion","clasificarPredicado"] },
    { id:"len-oracion-compuesta", trimestre:2, bloque:"Reflexión sobre la lengua", titulo:"La oración compuesta",
      saber:"Coordinación, yuxtaposición y subordinación.",
      entra:["Yuxtapuestas","Coordinadas: copulativas, adversativas, disyuntivas","Subordinadas sustantivas","Subordinadas adjetivas","Subordinadas adverbiales","Cómo reconocer cada una"],
      generadores:["clasificarCompuesta","identificarNexo","funcionSubordinada"] },
    { id:"len-morfologia", trimestre:1, bloque:"Reflexión sobre la lengua", titulo:"Categorías gramaticales",
      saber:"Clases de palabras y su funcionamiento.",
      entra:["Sustantivo, adjetivo, determinante","Pronombres","El verbo: conjugación, perífrasis","Adverbio, preposición, conjunción","Formación de palabras: derivación y composición"],
      generadores:["categoriaPalabra","perifrasis","formacionPalabras"] },
    { id:"len-lexico", trimestre:2, bloque:"Reflexión sobre la lengua", titulo:"Léxico y semántica",
      saber:"Relaciones semánticas y variación lingüística.",
      entra:["Sinonimia y antonimia","Polisemia y homonimia","Campo semántico","Connotación y denotación","Préstamos y neologismos","Variedades del español"],
      generadores:["relacionSemantica","polisemiaHomonimia","denotacion"] },
    { id:"len-ortografia", trimestre:3, bloque:"Reflexión sobre la lengua", titulo:"Ortografía y acentuación",
      saber:"Corrección ortográfica y gramatical.",
      entra:["Reglas de acentuación","Tilde diacrítica","Diptongos e hiatos","Puntuación: coma, punto y coma","Errores frecuentes: porque/por qué, sino/si no, haber/a ver"],
      generadores:["acentuar","tildeDiacritica","puntuacion","errorFrecuente"] },
    { id:"len-textos", trimestre:1, bloque:"Comunicación", titulo:"Tipos de texto y comentario",
      saber:"Comprensión y producción de textos.",
      entra:["Narrativo, descriptivo, expositivo, argumentativo","Estructura del texto","Coherencia y cohesión","Conectores","Tesis y argumentos","Cómo se comenta un texto"],
      generadores:["tipoTexto","conector","identificarTesis","tipoArgumento"] },
    { id:"len-siglo19", trimestre:2, bloque:"Literatura", titulo:"Romanticismo y Realismo",
      saber:"La literatura del siglo XIX.",
      entra:["Contexto del XIX","Romanticismo: Espronceda, Bécquer, Rosalía","Teatro romántico: Don Juan","Realismo y Naturalismo","Galdós y Clarín","Rasgos para reconocerlos"],
      generadores:["autorObra","rasgoMovimiento","fragmentoAMovimiento"] },
    { id:"len-siglo20", trimestre:3, bloque:"Literatura", titulo:"Literatura del siglo XX",
      saber:"Movimientos literarios del siglo XX.",
      entra:["Modernismo y 98: Machado, Baroja","Novecentismo y vanguardias","Generación del 27: Lorca, Alberti","Literatura de posguerra","Teatro: Valle-Inclán, Buero","Del boom a hoy"],
      generadores:["autorGeneracion","obraAutor","rasgoEpoca"] },
    { id:"len-metrica", trimestre:3, bloque:"Literatura", titulo:"Métrica y figuras literarias",
      saber:"Recursos del lenguaje literario.",
      entra:["Medir versos: sinalefa y acento final","Rima consonante y asonante","Estrofas: soneto, romance","Figuras: metáfora, hipérbaton, anáfora","Cómo se analiza un poema"],
      generadores:["medirVerso","tipoEstrofa","identificarFigura"] },
  ],

  /* ══════════════ INGLÉS (4º ESO, nivel B2+) ══════════════ */
  "Inglés B2+": [
    { id:"ing-tenses", trimestre:1, bloque:"Grammar", titulo:"Tiempos verbales: repaso completo",
      saber:"Uso de los tiempos verbales en contexto.",
      entra:["Present simple vs continuous","Past simple vs continuous","Present perfect vs past simple","Past perfect","Future: will, going to, present continuous","Future perfect y continuous"],
      generadores:["elegirTiempo","huecoVerbal","corregirFrase"] },
    { id:"ing-conditionals", trimestre:2, bloque:"Grammar", titulo:"Condicionales y wish",
      saber:"Expresión de hipótesis y deseos.",
      entra:["Zero, first, second, third conditional","Mixed conditionals","I wish / if only","Unless, as long as, provided that","Errores típicos del español"],
      generadores:["tipoCondicional","completarCondicional","wishRegret"] },
    { id:"ing-passive", trimestre:2, bloque:"Grammar", titulo:"Pasiva y estilo indirecto",
      saber:"Transformación de estructuras.",
      entra:["Pasiva en todos los tiempos","Pasiva con dos objetos","It is said that… / He is said to…","Reported speech: cambios","Reported questions y orders"],
      generadores:["aPasiva","aReported","preguntaReportada"] },
    { id:"ing-modals", trimestre:1, bloque:"Grammar", titulo:"Verbos modales",
      saber:"Obligación, posibilidad y deducción.",
      entra:["Must, have to, should","Can, could, be able to","May, might, could: posibilidad","Modal perfects: must have, should have","Deducción sobre el pasado"],
      generadores:["elegirModal","modalPerfect","deduccion"] },
    { id:"ing-relatives", trimestre:1, bloque:"Grammar", titulo:"Relative clauses",
      saber:"Oraciones de relativo definidas y no definidas.",
      entra:["Who, which, that, whose, where","Defining vs non-defining","Cuándo se puede omitir el pronombre","Preposición + relativo","Reduced relative clauses"],
      generadores:["elegirRelativo","unirFrases","definingONo"] },
    { id:"ing-use-of-english", trimestre:2, bloque:"Use of English", titulo:"Word formation y key word transformation",
      saber:"Transformación léxica y estructural.",
      entra:["Prefijos y sufijos","De verbo a sustantivo y adjetivo","Negative prefixes","Key word transformation: las 10 más frecuentes","Collocations"],
      generadores:["wordFormation","keyWordTransformation","collocation"] },
    { id:"ing-phrasal", trimestre:3, bloque:"Vocabulary", titulo:"Phrasal verbs y preposiciones",
      saber:"Léxico de alta frecuencia.",
      entra:["Phrasal verbs por partícula","Separables e inseparables","Los 50 más usados","Dependent prepositions","Idioms frecuentes"],
      generadores:["phrasalHueco","preposicionDependiente","significadoPhrasal"] },
    { id:"ing-writing", trimestre:3, bloque:"Writing", titulo:"Writing: essay, email y review",
      saber:"Producción escrita formal e informal.",
      entra:["Opinion essay: estructura en 4 párrafos","Conectores formales","Formal email vs informal","Review: film, book, restaurant","Article y report","Qué puntúa el examinador"],
      generadores:["elegirConector","registroFormal","ordenarParrafos"] },
    { id:"ing-speaking", trimestre:3, bloque:"Speaking", titulo:"Speaking: cómo se aprueba",
      saber:"Interacción oral y estrategias.",
      entra:["Las 4 partes del examen","Comparar dos fotos","Dar opinión y matizarla","Estar de acuerdo y discrepar","Ganar tiempo sin callarse","Errores que bajan la nota"],
      generadores:["frasesUtiles","compararFotos"] },
  ],

  /* ══════════════ TECNOLOGÍA Y DIGITALIZACIÓN ══════════════ */
  "Tecnología y Digitalización": [
    { id:"tec-programacion", trimestre:1, bloque:"Pensamiento computacional", titulo:"Programación",
      saber:"Resolución de problemas mediante algoritmos y programación.",
      entra:["Variables y tipos","Condicionales","Bucles","Funciones","Listas","Depurar: leer el error"],
      generadores:["queImprime","completarCodigo","encontrarError","trazaBucle"] },
    { id:"tec-electronica", trimestre:1, bloque:"Electrónica", titulo:"Circuitos y electrónica",
      saber:"Circuitos eléctricos y electrónicos básicos.",
      entra:["Ley de Ohm","Serie y paralelo","Potencia y energía consumida","Resistencias, LED, diodo, transistor","Leer un esquema","Montar un circuito"],
      generadores:["leyOhm","serieParalelo","potenciaConsumo","codigoColores"] },
    { id:"tec-robotica", trimestre:2, bloque:"Control", titulo:"Robótica y sistemas de control",
      saber:"Sistemas automáticos y de control.",
      entra:["Sistema de control: entrada, proceso, salida","Sensores y actuadores","Lazo abierto y cerrado","Arduino: pines y funciones","Programar un robot"],
      generadores:["sensorOActuador","lazoControl","codigoArduino"] },
    { id:"tec-mecanismos", trimestre:2, bloque:"Máquinas", titulo:"Mecanismos y máquinas",
      saber:"Transmisión y transformación del movimiento.",
      entra:["Palanca y sus géneros","Poleas y polipastos","Engranajes y relación de transmisión","Piñón-cremallera, tornillo sin fin","Leva y biela-manivela"],
      generadores:["palanca","relacionTransmision","tipoMecanismo"] },
    { id:"tec-3d", trimestre:3, bloque:"Diseño", titulo:"Diseño e impresión 3D",
      saber:"Diseño asistido por ordenador y fabricación digital.",
      entra:["Vistas: alzado, planta, perfil","Acotación","Escalas","Del diseño al STL","Parámetros de impresión"],
      generadores:["vistas","acotar","escalaPieza"] },
    { id:"tec-redes", trimestre:3, bloque:"Digitalización", titulo:"Redes, internet y ciberseguridad",
      saber:"Comunicación digital y seguridad.",
      entra:["Cómo viaja un dato: IP, DNS, HTTP","Redes: LAN, WAN, wifi","Contraseñas y doble factor","Phishing e ingeniería social","Huella digital","Licencias y derechos de autor"],
      generadores:["identificarAtaque","protocolos","seguridadContrasena"] },
  ],

  /* ══════════════ GEOGRAFÍA E HISTORIA ══════════════ */
  "Geografía e Historia": [
    { id:"his-xix", trimestre:1, bloque:"El mundo contemporáneo", titulo:"El siglo XIX: revoluciones e industria",
      saber:"Transformaciones políticas y económicas del XIX.",
      entra:["Revolución Francesa y Napoleón","Revolución Industrial","Movimiento obrero","Nacionalismos: Italia y Alemania","Imperialismo","España en el XIX"],
      generadores:["ordenarCronologia","causaConsecuencia","identificarConcepto"] },
    { id:"his-guerras", trimestre:2, bloque:"El mundo contemporáneo", titulo:"Las guerras mundiales",
      saber:"Los grandes conflictos del siglo XX.",
      entra:["Causas de la Primera Guerra Mundial","Revolución Rusa","Entreguerras: crisis del 29","Fascismo y nazismo","Segunda Guerra Mundial","El Holocausto"],
      generadores:["ordenarCronologia","causaConsecuencia","mapaBandos"] },
    { id:"his-espana-xx", trimestre:2, bloque:"España", titulo:"España en el siglo XX",
      saber:"De la Restauración a la democracia.",
      entra:["Restauración y crisis del 98","Segunda República","Guerra Civil","Franquismo","Transición","Constitución de 1978"],
      generadores:["ordenarCronologia","etapaHistorica","identificarConcepto"] },
    { id:"his-guerrafria", trimestre:3, bloque:"El mundo actual", titulo:"Guerra Fría y descolonización",
      saber:"El mundo bipolar y sus conflictos.",
      entra:["Bloques y telón de acero","Crisis: Berlín, Cuba, Vietnam","Descolonización","Caída del muro y de la URSS","Construcción de la Unión Europea"],
      generadores:["ordenarCronologia","bloqueGuerraFria","causaConsecuencia"] },
    { id:"geo-globalizacion", trimestre:3, bloque:"El mundo actual", titulo:"Globalización y retos del siglo XXI",
      saber:"Interdependencia y desigualdad en el mundo actual.",
      entra:["Qué es la globalización","Desigualdad Norte-Sur","Migraciones","Cambio climático","Objetivos de Desarrollo Sostenible","Interpretación de gráficos y mapas"],
      generadores:["leerGrafico","indicadorDesarrollo","identificarConcepto"] },
  ],
};

/* Estado: cuántos hay y cuántos hechos */
function estadoCurriculo(){
  const hechos = (typeof TEMAS !== "undefined" ? TEMAS : []).filter(t => t.estado === "listo").map(t => t.id);
  const todos = Object.values(CURRICULO).flat();
  return {total: todos.length, hechos: todos.filter(t => hechos.includes(t.id)).length, lista: todos, hechosIds: hechos};
}
