/* preguntas-pot.js — potencias y notación científica. */
BANCO.push(
  { id:"pot-01", tema:"mat-b-potencias", etiqueta:"Propiedades",
    enunciado:"$2^3 \\cdot 2^4$ es igual a…",
    opciones:[{texto:"$2^7$", bien:true},
      {texto:"$4^7$", porque:"La base no se multiplica: se queda igual. Solo se suman los exponentes."},
      {texto:"$2^{12}$", porque:"Eso sería $(2^3)^4$: al multiplicar potencias se suman, no se multiplican."},
      {texto:"$4^{12}$", porque:"Dos errores a la vez."}],
    porque:"Misma base multiplicando: se suman los exponentes. 3 + 4 = 7." },

  { id:"pot-02", tema:"mat-b-potencias", etiqueta:"Propiedades",
    enunciado:"$(3^2)^4$ es igual a…",
    opciones:[{texto:"$3^8$", bien:true},
      {texto:"$3^6$", porque:"Los has sumado. En una potencia de otra potencia se multiplican."},
      {texto:"$9^4$", porque:"Es cierto que $3^2=9$, pero la forma pedida mantiene la base 3: $3^8$."},
      {texto:"$3^{16}$", porque:"Has elevado 4 al cuadrado o similar. Es 2 × 4."}],
    porque:"Potencia de una potencia: los exponentes se multiplican. 2 × 4 = 8." },

  { id:"pot-03", tema:"mat-b-potencias", etiqueta:"Exponente cero",
    enunciado:"$7^0$ vale…",
    opciones:[{texto:"1", bien:true},
      {texto:"0", porque:"Es el error más repetido. Cualquier número (distinto de cero) elevado a 0 da 1."},
      {texto:"7", porque:"Eso sería $7^1$."},
      {texto:"No existe", porque:"Sí existe y vale 1."}],
    porque:"Sale de la regla del cociente: $\\frac{7^3}{7^3} = 7^0$, y también es 1 porque algo dividido entre sí mismo da 1." },

  { id:"pot-04", tema:"mat-b-potencias", etiqueta:"Exponente negativo",
    enunciado:"$5^{-2}$ vale…",
    opciones:[{texto:"$\\dfrac{1}{25}$", bien:true},
      {texto:"$-25$", porque:"El signo menos del exponente no hace negativo el resultado: lo manda al denominador."},
      {texto:"$-10$", porque:"Ni multiplica ni cambia el signo: invierte."},
      {texto:"$\\dfrac{1}{10}$", porque:"Hay que elevar al cuadrado, no multiplicar por 2."}],
    porque:"Exponente negativo significa «uno partido por»: $5^{-2} = \\frac{1}{5^2} = \\frac{1}{25}$." },

  { id:"pot-05", tema:"mat-b-potencias", etiqueta:"Signos",
    enunciado:"¿Cuál es la diferencia entre $(-2)^4$ y $-2^4$?",
    opciones:[{texto:"La primera da 16 y la segunda −16", bien:true},
      {texto:"Ninguna, son lo mismo", porque:"El paréntesis cambia todo: decide si el signo se eleva o no."},
      {texto:"Las dos dan 16", porque:"En la segunda el menos queda fuera: es −(2⁴)."},
      {texto:"Las dos dan −16", porque:"En la primera se eleva el −2 entero, y menos por menos cuatro veces da positivo."}],
    porque:"Con paréntesis se eleva el −2 entero (par → positivo). Sin paréntesis, el menos multiplica al final." },

  { id:"pot-06", tema:"mat-b-potencias", etiqueta:"Notación científica",
    enunciado:"¿Cuál de estos números está bien escrito en notación científica?",
    opciones:[{texto:"$3{,}5 \\cdot 10^{6}$", bien:true},
      {texto:"$35 \\cdot 10^{5}$", porque:"La parte de delante tiene que estar entre 1 y 10. El 35 se pasa."},
      {texto:"$0{,}35 \\cdot 10^{7}$", porque:"0,35 es menor que 1: tampoco vale."},
      {texto:"$3{,}5 \\cdot 6^{10}$", porque:"La base tiene que ser 10 siempre."}],
    porque:"Notación científica: un número entre 1 y 10 (con una sola cifra antes de la coma) por una potencia de 10." },

  { id:"pot-07", tema:"mat-b-potencias", etiqueta:"Notación científica",
    enunciado:"0,00042 en notación científica es…",
    opciones:[{texto:"$4{,}2 \\cdot 10^{-4}$", bien:true},
      {texto:"$4{,}2 \\cdot 10^{4}$", porque:"Es un número pequeño: el exponente tiene que ser negativo."},
      {texto:"$42 \\cdot 10^{-5}$", porque:"El 42 se pasa de 10: hay que dejar una sola cifra delante de la coma."},
      {texto:"$0{,}42 \\cdot 10^{-3}$", porque:"0,42 es menor que 1."}],
    porque:"La coma se mueve 4 lugares a la derecha para dejar el 4,2, así que el exponente es −4." },

  { id:"pot-08", tema:"mat-b-potencias", etiqueta:"Operar",
    enunciado:"$(2 \\cdot 10^{5}) \\cdot (3 \\cdot 10^{4})$ es…",
    opciones:[{texto:"$6 \\cdot 10^{9}$", bien:true},
      {texto:"$6 \\cdot 10^{20}$", porque:"Los exponentes se suman, no se multiplican."},
      {texto:"$5 \\cdot 10^{9}$", porque:"Los números de delante se multiplican (2 × 3), no se suman."},
      {texto:"$6 \\cdot 10^{-1}$", porque:"Los has restado, y aquí se multiplica."}],
    porque:"Se multiplican las partes decimales (2 × 3 = 6) y se suman los exponentes (5 + 4 = 9)." },

  { id:"pot-09", tema:"mat-b-potencias", etiqueta:"Operar",
    enunciado:"Al multiplicar dos números en notación científica sale $35 \\cdot 10^{7}$. ¿Qué falta?",
    opciones:[{texto:"Ajustarlo a $3{,}5 \\cdot 10^{8}$", bien:true},
      {texto:"Nada, ya está bien", porque:"La parte de delante debe estar entre 1 y 10, y 35 no lo está."},
      {texto:"Convertirlo en $3{,}5 \\cdot 10^{6}$", porque:"Al mover la coma a la izquierda el exponente sube, no baja."},
      {texto:"Convertirlo en $0{,}35 \\cdot 10^{8}$", porque:"0,35 es menor que 1."}],
    porque:"Se mueve la coma un lugar a la izquierda y se compensa subiendo el exponente en uno." },

  { id:"pot-10", tema:"mat-b-potencias", etiqueta:"Orden de magnitud",
    enunciado:"Un virus mide $10^{-7}$ m y una célula $10^{-5}$ m. La célula es…",
    opciones:[{texto:"100 veces mayor", bien:true},
      {texto:"2 veces mayor", porque:"La diferencia de exponentes es 2, pero eso significa 10², no 2."},
      {texto:"10 veces mayor", porque:"Serían 10 veces si la diferencia fuera de un solo exponente."},
      {texto:"1.000 veces mayor", porque:"Eso sería una diferencia de tres exponentes."}],
    porque:"$10^{-5} / 10^{-7} = 10^{2} = 100$. Cada salto de exponente multiplica por diez." },

  { id:"pot-11", tema:"mat-b-potencias", etiqueta:"Sentido",
    enunciado:"¿Para qué sirve la notación científica?",
    opciones:[{texto:"Para escribir y comparar números muy grandes o muy pequeños sin equivocarse de ceros", bien:true},
      {texto:"Para que los números parezcan más difíciles", porque:"Es justo al revés: simplifica."},
      {texto:"Para redondear", porque:"Redondear es otra cosa, aunque suelan ir juntas."},
      {texto:"Solo se usa en física", porque:"Se usa en economía, informática, biología… en todas partes."}],
    porque:"Escribir 0,000000001 invita a equivocarse contando ceros. Escribir 10⁻⁹ no." },

  { id:"pot-12", tema:"mat-b-potencias", etiqueta:"Fracciones",
    enunciado:"$\\left(\\dfrac{2}{3}\\right)^{-2}$ vale…",
    opciones:[{texto:"$\\dfrac{9}{4}$", bien:true},
      {texto:"$\\dfrac{4}{9}$", porque:"Eso sería con exponente +2. El negativo primero da la vuelta a la fracción."},
      {texto:"$-\\dfrac{4}{9}$", porque:"El exponente negativo no cambia el signo."},
      {texto:"$\\dfrac{2}{9}$", porque:"Hay que elevar los dos, numerador y denominador."}],
    porque:"Exponente negativo en una fracción: se le da la vuelta y se eleva. $(3/2)^2 = 9/4$." },

  { id:"pot-13", tema:"mat-b-potencias", etiqueta:"Unidades",
    enunciado:"3 nanómetros en metros son…",
    opciones:[{texto:"$3 \\cdot 10^{-9}$ m", bien:true},
      {texto:"$3 \\cdot 10^{9}$ m", porque:"Un nanómetro es pequeñísimo: el exponente es negativo."},
      {texto:"$3 \\cdot 10^{-6}$ m", porque:"Eso son micrómetros; el nano es mil veces menor."},
      {texto:"$3 \\cdot 10^{-3}$ m", porque:"Eso son milímetros."}],
    porque:"Nano significa $10^{-9}$. Micro es $10^{-6}$ y mili es $10^{-3}$." },

  { id:"pot-14", tema:"mat-b-potencias", etiqueta:"Problema",
    enunciado:"La luz recorre $3 \\cdot 10^{8}$ m en un segundo. ¿Cuánto recorre en 100 segundos?",
    opciones:[{texto:"$3 \\cdot 10^{10}$ m", bien:true},
      {texto:"$3 \\cdot 10^{800}$ m", porque:"No se elevan los exponentes: se multiplica por 100, que es 10²."},
      {texto:"$300 \\cdot 10^{8}$ m", porque:"Es correcto en valor, pero no está en notación científica: hay que ajustar a $3 \\cdot 10^{10}$."},
      {texto:"$3 \\cdot 10^{6}$ m", porque:"Has dividido. Recorre más, no menos."}],
    porque:"$3 \\cdot 10^{8} \\cdot 10^{2} = 3 \\cdot 10^{10}$ metros, o sea 30 millones de kilómetros." }
);
