/* preguntas-ecu.js — banco de ecuaciones de segundo grado y otras. */
BANCO.push(
  { id:"ecu-01", tema:"mat-b-ecuaciones", etiqueta:"Discriminante",
    enunciado:"Si el discriminante Δ = b² − 4ac es negativo, la ecuación…",
    opciones:[{texto:"No tiene soluciones reales", bien:true},
      {texto:"Tiene dos soluciones negativas", porque:"El signo de Δ no dice el signo de las soluciones: dice cuántas hay. Con Δ < 0 habría que hacer la raíz de un negativo."},
      {texto:"Tiene una solución doble", porque:"Eso es con Δ = 0."},
      {texto:"Tiene infinitas soluciones", porque:"Una ecuación de segundo grado tiene como mucho dos."}],
    porque:"La fórmula lleva √Δ. Si Δ es negativo, esa raíz no existe en los números reales." },

  { id:"ecu-02", tema:"mat-b-ecuaciones", etiqueta:"Incompletas",
    enunciado:"Resolviendo x² = 5x, un compañero divide entre x y obtiene x = 5. ¿Qué ha hecho mal?",
    opciones:[{texto:"Ha perdido la solución x = 0", bien:true},
      {texto:"Nada, x = 5 es la única", porque:"Sustituye x = 0: 0² = 5·0 → 0 = 0. También vale."},
      {texto:"Tenía que salir x = −5", porque:"(−5)² = 25 y 5·(−5) = −25: no cumple."},
      {texto:"Debería haber usado la fórmula general", porque:"Se puede, pero sacar factor común es más rápido. El fallo no es el método, es dividir entre x."}],
    porque:"Dividir entre x solo es legal si x ≠ 0, y justo x = 0 es solución. Lo correcto: x² − 5x = 0 → x(x − 5) = 0 → x = 0 o x = 5." },

  { id:"ecu-03", tema:"mat-b-ecuaciones", etiqueta:"Incompletas",
    enunciado:"¿Cuáles son las soluciones de x² − 49 = 0?",
    opciones:[{texto:"x = 7 y x = −7", bien:true},
      {texto:"Solo x = 7", porque:"(−7)² también es 49. Al hacer la raíz hay que poner ±."},
      {texto:"x = 49", porque:"Has despejado x² pero no has hecho la raíz."},
      {texto:"No tiene solución", porque:"No tendría si fuera x² + 49 = 0."}],
    porque:"x² = 49 → x = ±√49 = ±7." },

  { id:"ecu-04", tema:"mat-b-ecuaciones", etiqueta:"Fórmula",
    enunciado:"En 2x² − 3x − 5 = 0, ¿cuánto valen a, b y c?",
    opciones:[{texto:"a = 2, b = −3, c = −5", bien:true},
      {texto:"a = 2, b = 3, c = 5", porque:"Los signos van con el número. Olvidarlos es el fallo más caro del tema."},
      {texto:"a = 2, b = −3, c = 0", porque:"El término independiente es −5."},
      {texto:"a = −3, b = 2, c = −5", porque:"a es siempre el que acompaña a x²."}],
    porque:"a va con x², b con x y c es el número solo, cada uno con su signo." },

  { id:"ecu-05", tema:"mat-b-ecuaciones", etiqueta:"Fórmula",
    enunciado:"¿Cuántas soluciones tiene x² − 6x + 9 = 0?",
    opciones:[{texto:"Una (doble): x = 3", bien:true},
      {texto:"Dos: 3 y −3", porque:"Sustituye −3: 9 + 18 + 9 = 36 ≠ 0."},
      {texto:"Ninguna", porque:"Δ = 36 − 36 = 0, no negativo."},
      {texto:"Dos: 6 y 9", porque:"Has confundido los coeficientes con las soluciones."}],
    porque:"Δ = (−6)² − 4·1·9 = 0: una única solución, x = 6/2 = 3. De hecho es (x − 3)²." },

  { id:"ecu-06", tema:"mat-b-ecuaciones", etiqueta:"Bicuadradas",
    enunciado:"Para resolver x⁴ − 5x² + 4 = 0 lo primero es…",
    opciones:[{texto:"Hacer el cambio t = x²", bien:true},
      {texto:"Hacer la raíz cuarta", porque:"Hay tres términos: no se puede despejar x⁴ solo."},
      {texto:"Aplicar la fórmula con a = 1, b = −5, c = 4 y ya está", porque:"Esa fórmula te da t, no x. Falta deshacer el cambio."},
      {texto:"Dividir entre x²", porque:"Te deja términos con 1/x² y lo complica."}],
    porque:"Con t = x² queda t² − 5t + 4 = 0 → t = 1 y t = 4 → x = ±1 y x = ±2." },

  { id:"ecu-07", tema:"mat-b-ecuaciones", etiqueta:"Bicuadradas",
    enunciado:"Tras el cambio, sale t = 9 y t = −4. ¿Cuáles son las soluciones en x?",
    opciones:[{texto:"x = 3 y x = −3", bien:true},
      {texto:"x = 3, −3, 2 y −2", porque:"x² = −4 no tiene solución: ningún número al cuadrado da negativo."},
      {texto:"x = 9 y x = −4", porque:"Esas son las de t. Falta hacer la raíz."},
      {texto:"x = 3 y x = 2", porque:"Te faltan los negativos y sobra el 2."}],
    porque:"x² = 9 → x = ±3. x² = −4 → sin solución real. Quedan dos." },

  { id:"ecu-08", tema:"mat-b-ecuaciones", etiqueta:"Radicales",
    enunciado:"¿Por qué hay que comprobar las soluciones de una ecuación con radicales?",
    opciones:[{texto:"Porque elevar al cuadrado puede meter soluciones falsas", bien:true},
      {texto:"Porque la fórmula general a veces falla", porque:"La fórmula no falla. Lo que cambia la ecuación es elevar al cuadrado."},
      {texto:"Para asegurarse de que no hay errores de cuentas", porque:"También ayuda, pero aunque no te equivoques puede aparecer una solución que no vale."},
      {texto:"No hace falta si Δ > 0", porque:"Δ no tiene nada que ver con las soluciones falsas."}],
    porque:"Al elevar, √A = B se convierte en A = B², que también cumple quien tenga √A = −B. Esas «soluciones» no son de la ecuación original." },

  { id:"ecu-09", tema:"mat-b-ecuaciones", etiqueta:"Radicales",
    enunciado:"Resolviendo √(x + 2) = x sale x = 2 y x = −1. ¿Cuál vale?",
    opciones:[{texto:"Solo x = 2", bien:true},
      {texto:"Las dos", porque:"Con x = −1: √1 = 1, pero el lado derecho es −1. 1 ≠ −1."},
      {texto:"Solo x = −1", porque:"Con x = 2: √4 = 2 = x. Esta sí vale."},
      {texto:"Ninguna", porque:"x = 2 cumple perfectamente."}],
    porque:"Comprobando: x = 2 → √4 = 2 ✓. x = −1 → √1 = 1 ≠ −1 ✗. La raíz cuadrada nunca da negativo." },

  { id:"ecu-10", tema:"mat-b-ecuaciones", etiqueta:"Fracciones",
    enunciado:"Para quitar las fracciones de x + 6/x = 5, se multiplica todo por…",
    opciones:[{texto:"x, sabiendo que x no puede ser 0", bien:true},
      {texto:"6", porque:"Seguiría quedando la x en el denominador."},
      {texto:"5x²", porque:"Funciona pero complica: basta con el denominador, x."},
      {texto:"No se puede quitar", porque:"Multiplicando por el denominador desaparece."}],
    porque:"x² + 6 = 5x → x² − 5x + 6 = 0 → x = 2 y x = 3. Y hay que vigilar que ninguna sea la que anula el denominador." },

  { id:"ecu-11", tema:"mat-b-ecuaciones", etiqueta:"Problemas",
    enunciado:"Un rectángulo tiene 3 m más de largo que de ancho y 40 m² de área. Sale x = 5 y x = −8. ¿Cuánto mide el ancho?",
    opciones:[{texto:"5 m", bien:true},
      {texto:"5 m o −8 m", porque:"Una longitud no puede ser negativa. La ecuación da dos, pero el problema solo admite una."},
      {texto:"8 m", porque:"Has quitado el signo de −8: esa no es solución del problema."},
      {texto:"8 m, que es el largo", porque:"El largo es 5 + 3 = 8, pero te preguntan el ancho."}],
    porque:"x(x + 3) = 40 da dos soluciones matemáticas; el contexto descarta la negativa. Siempre hay que volver al enunciado." },

  { id:"ecu-12", tema:"mat-b-ecuaciones", etiqueta:"Fórmula",
    enunciado:"Aplicando la fórmula a x² + 2x − 8 = 0, ¿qué da √Δ?",
    opciones:[{texto:"6", bien:true},
      {texto:"√−28", porque:"Δ = 4 − 4·1·(−8) = 4 + 32. El −8 cambia de signo al multiplicar por −4."},
      {texto:"2", porque:"Has olvidado el término −4ac."},
      {texto:"36", porque:"36 es Δ; te piden su raíz."}],
    porque:"Δ = 2² − 4·1·(−8) = 36 → √Δ = 6 → x = (−2 ± 6)/2 → x = 2 y x = −4." }
);
