/* preguntas-modales.js — verbos modales. */
BANCO.push(
  { id:"mod-01", tema:"ing-modals", etiqueta:"Forma",
    enunciado:"¿Cuál es correcta?",
    opciones:[{texto:"She can swim", bien:true},
      {texto:"She cans swim", porque:"Los modales no llevan «s» en tercera persona. Nunca."},
      {texto:"She can to swim", porque:"Detrás de un modal va el infinitivo sin «to»."},
      {texto:"She can swims", porque:"El verbo que sigue al modal va sin «s»."}],
    porque:"Los modales no cambian nunca y van seguidos de infinitivo sin «to»." },

  { id:"mod-02", tema:"ing-modals", etiqueta:"Obligación",
    enunciado:"«You mustn't park here» significa…",
    opciones:[{texto:"Está prohibido aparcar aquí", bien:true},
      {texto:"No hace falta aparcar aquí", porque:"Eso sería «you don't have to park here». Confundirlos es el error clásico."},
      {texto:"Puedes aparcar si quieres", porque:"Al contrario: está prohibido."},
      {texto:"Deberías aparcar en otro sitio", porque:"Eso sería «should», que es un consejo, no una prohibición."}],
    porque:"«Mustn't» es prohibición. «Don't have to» es que no hace falta. En español los dos suenan parecido y por eso se falla." },

  { id:"mod-03", tema:"ing-modals", etiqueta:"Obligación",
    enunciado:"«You don't have to come» significa…",
    opciones:[{texto:"No es obligatorio venir, pero puedes", bien:true},
      {texto:"No puedes venir", porque:"Eso sería «you mustn't come» o «you can't come»."},
      {texto:"Tienes que venir", porque:"Justo lo contrario: la negación quita la obligación."},
      {texto:"Deberías venir", porque:"Eso sería «you should come»."}],
    porque:"«Don't have to» quita la obligación pero no prohíbe nada: vienes si te apetece." },

  { id:"mod-04", tema:"ing-modals", etiqueta:"Must o have to",
    enunciado:"¿Cuál es la diferencia entre «must» y «have to»?",
    opciones:[{texto:"«Must» sale de quien habla; «have to», de una norma externa", bien:true},
      {texto:"Ninguna, son idénticos", porque:"En afirmativa se parecen, pero en negativa significan cosas opuestas."},
      {texto:"«Must» es pasado", porque:"«Must» no tiene pasado: para eso se usa «had to»."},
      {texto:"«Have to» es más formal", porque:"Si acaso es al revés: «must» suena más formal."}],
    porque:"«I must study» (lo decido yo) frente a «I have to work on Saturdays» (me lo imponen). Y en negativa ya son cosas distintas." },

  { id:"mod-05", tema:"ing-modals", etiqueta:"Deducción",
    enunciado:"«He's not answering. He ____ be asleep.» (casi seguro que sí)",
    opciones:[{texto:"must", bien:true},
      {texto:"mustn't", porque:"Para deducir que NO, se usa «can't». «Mustn't» es prohibición."},
      {texto:"should", porque:"«Should» sería un consejo o una expectativa, no una deducción."},
      {texto:"can", porque:"«Can» es habilidad o permiso, no deducción."}],
    porque:"La escala de deducción: must (seguro que sí) · might/may/could (quizá) · can't (seguro que no)." },

  { id:"mod-06", tema:"ing-modals", etiqueta:"Deducción",
    enunciado:"«That ____ be Ana. She's in Japan.» (seguro que no)",
    opciones:[{texto:"can't", bien:true},
      {texto:"mustn't", porque:"Este es EL error: «mustn't» prohíbe, no deduce. Para «seguro que no» va «can't»."},
      {texto:"couldn't", porque:"Se entiende, pero la forma normal para deducción presente es «can't»."},
      {texto:"shouldn't", porque:"Eso sería un consejo en negativo."}],
    porque:"Para decir que algo es imposible se usa «can't», nunca «mustn't»." },

  { id:"mod-07", tema:"ing-modals", etiqueta:"Modal perfect",
    enunciado:"«She ____ studied a lot. She got the best mark.»",
    opciones:[{texto:"must have", bien:true},
      {texto:"must", porque:"Falta «have»: sin él, la frase habla del presente, no del pasado."},
      {texto:"should have", porque:"Eso sería un reproche: «debería haber estudiado», y aquí sacó la mejor nota."},
      {texto:"had to", porque:"«Had to» es obligación pasada, no deducción."}],
    porque:"Deducción sobre el pasado: must + have + participio. «Seguro que estudió mucho»." },

  { id:"mod-08", tema:"ing-modals", etiqueta:"Modal perfect",
    enunciado:"«You should have told me» significa…",
    opciones:[{texto:"Deberías habérmelo dicho (y no lo hiciste)", bien:true},
      {texto:"Deberías decírmelo", porque:"Eso es «you should tell me», en presente."},
      {texto:"Me lo dijiste", porque:"Justo al revés: la frase implica que no lo hizo."},
      {texto:"Tenías que decírmelo por obligación", porque:"«Should» es consejo o reproche, no obligación."}],
    porque:"«Should have + participio» habla de algo que no se hizo y habría estado bien hacer. Es reproche o arrepentimiento." },

  { id:"mod-09", tema:"ing-modals", etiqueta:"Habilidad",
    enunciado:"Para decir «pude hacerlo» (lo conseguí una vez concreta) se usa…",
    opciones:[{texto:"was able to / managed to", bien:true},
      {texto:"could", porque:"«Could» es habilidad general en el pasado: «sabía hacerlo», no «lo conseguí aquella vez»."},
      {texto:"can", porque:"«Can» es presente."},
      {texto:"should", porque:"«Should» es consejo."}],
    porque:"«I could swim at five» (sabía nadar) frente a «I was able to swim across the river» (lo logré aquel día)." },

  { id:"mod-10", tema:"ing-modals", etiqueta:"Peticiones",
    enunciado:"¿Cuál suena más educado para pedir algo?",
    opciones:[{texto:"Could you help me, please?", bien:true},
      {texto:"Can you help me?", porque:"Vale, pero es más directo. «Could» suaviza."},
      {texto:"You must help me", porque:"Eso es una orden, no una petición."},
      {texto:"Help me", porque:"Es un imperativo: suena brusco."}],
    porque:"«Could» y «would» hacen las peticiones más educadas. En un examen oral, eso puntúa." },

  { id:"mod-11", tema:"ing-modals", etiqueta:"Posibilidad",
    enunciado:"«It may rain» y «It might rain»…",
    opciones:[{texto:"Significan casi lo mismo: quizá llueva", bien:true},
      {texto:"«May» es seguro y «might» imposible", porque:"Los dos expresan posibilidad; la diferencia es mínima."},
      {texto:"«Might» es pasado de «may»", porque:"Históricamente sí, pero hoy los dos hablan del presente o del futuro."},
      {texto:"«May» solo sirve para pedir permiso", porque:"También, pero además expresa posibilidad."}],
    porque:"Los dos valen para posibilidad; «might» suena algo menos probable. Y «may» sirve además para permiso formal." },

  { id:"mod-12", tema:"ing-modals", etiqueta:"Pasado",
    enunciado:"El pasado de «must» (obligación) es…",
    opciones:[{texto:"had to", bien:true},
      {texto:"musted", porque:"Los modales no se conjugan: esa forma no existe."},
      {texto:"must have", porque:"Eso es deducción sobre el pasado, no obligación pasada."},
      {texto:"should have", porque:"Eso es reproche."}],
    porque:"«Must» no tiene pasado propio: se usa «had to». «I had to work yesterday»." },

  { id:"mod-13", tema:"ing-modals", etiqueta:"Consejo",
    enunciado:"«You ought to see a doctor» equivale a…",
    opciones:[{texto:"You should see a doctor", bien:true},
      {texto:"You must see a doctor", porque:"«Ought to» es consejo, como «should», no obligación."},
      {texto:"You can see a doctor", porque:"«Can» sería permiso o posibilidad."},
      {texto:"You might see a doctor", porque:"Eso sería posibilidad, no consejo."}],
    porque:"«Ought to» significa lo mismo que «should», y es el único modal que lleva «to» detrás." },

  { id:"mod-14", tema:"ing-modals", etiqueta:"Problema",
    enunciado:"Tu amigo llega empapado. ¿Qué dices?",
    opciones:[{texto:"It must have been raining", bien:true},
      {texto:"It must be raining", porque:"Se puede, pero si ya está dentro y empapado, lo que deduces es sobre el rato anterior."},
      {texto:"It mustn't have rained", porque:"«Mustn't» no sirve para deducir. Y además contradice lo que ves."},
      {texto:"It should have rained", porque:"«Should have» es reproche: no encaja aquí."}],
    porque:"Deducción sobre algo que pasó justo antes: must + have + -ing para lo que estaba ocurriendo." }
);
