/* preguntas-log.js — banco de logaritmos. */
BANCO.push(
  { id:"log-01", tema:"mat-b-logaritmos", etiqueta:"Definición",
    enunciado:"$\\log_2 32$ vale…",
    opciones:[{texto:"5", bien:true},
      {texto:"16", porque:"Has dividido 32 entre 2. El logaritmo no divide: pregunta por el exponente."},
      {texto:"64", porque:"Has multiplicado. La respuesta es un exponente pequeño, no un número grande."},
      {texto:"2", porque:"2 es la base, no la respuesta."}],
    porque:"Porque $2^5 = 32$. El logaritmo es el exponente al que hay que elevar la base." },

  { id:"log-02", tema:"mat-b-logaritmos", etiqueta:"Definición",
    enunciado:"$\\log_a 1$ vale, para cualquier base $a$…",
    opciones:[{texto:"0", bien:true},
      {texto:"1", porque:"$\\log_a a = 1$, pero aquí el argumento es 1, no la base."},
      {texto:"$a$", porque:"El resultado de un logaritmo es un exponente, no la base."},
      {texto:"No existe", porque:"Sí existe y es de los más fáciles."}],
    porque:"Cualquier número elevado a 0 da 1, así que el exponente buscado es 0." },

  { id:"log-03", tema:"mat-b-logaritmos", etiqueta:"Existencia",
    enunciado:"¿Cuál de estos NO existe?",
    opciones:[{texto:"$\\log_2 (-8)$", bien:true},
      {texto:"$\\log_2 0{,}5$", porque:"Sí existe: vale $-1$, porque $2^{-1} = 0{,}5$. Los logaritmos pueden ser negativos."},
      {texto:"$\\log_{10} 1$", porque:"Existe y vale 0."},
      {texto:"$\\log_3 3$", porque:"Existe y vale 1."}],
    porque:"No hay ningún exponente que haga que 2 dé un número negativo: el argumento de un logaritmo siempre es positivo." },

  { id:"log-04", tema:"mat-b-logaritmos", etiqueta:"Propiedades",
    enunciado:"$\\log 20 + \\log 5$ es igual a…",
    opciones:[{texto:"$\\log 100 = 2$", bien:true},
      {texto:"$\\log 25$", porque:"Sumar logaritmos es multiplicar los argumentos, no sumarlos."},
      {texto:"$\\log 4$", porque:"Eso sería una resta: $\\log 20 - \\log 5$."},
      {texto:"$2\\log 25$", porque:"No hay ninguna propiedad que haga eso."}],
    porque:"La suma de logaritmos es el logaritmo del producto: $20 \\cdot 5 = 100$, y $\\log 100 = 2$." },

  { id:"log-05", tema:"mat-b-logaritmos", etiqueta:"Propiedades",
    enunciado:"$\\log x^3$ es igual a…",
    opciones:[{texto:"$3\\log x$", bien:true},
      {texto:"$(\\log x)^3$", porque:"No es lo mismo elevar el argumento que elevar el logaritmo entero."},
      {texto:"$\\log 3x$", porque:"Eso sería multiplicar por 3 dentro, no elevar."},
      {texto:"$\\dfrac{\\log x}{3}$", porque:"Dividir sería para una raíz: $\\log \\sqrt[3]{x} = \\frac13 \\log x$."}],
    porque:"El exponente de dentro sale fuera multiplicando. Es la propiedad que más se usa." },

  { id:"log-06", tema:"mat-b-logaritmos", etiqueta:"Error típico",
    enunciado:"$\\log(a + b)$ es igual a…",
    opciones:[{texto:"No se puede descomponer", bien:true},
      {texto:"$\\log a + \\log b$", porque:"Este es EL error del tema. $\\log a + \\log b$ es $\\log(a \\cdot b)$, no $\\log(a+b)$. Compruébalo: $\\log(10+10)=\\log 20 \\approx 1{,}3$, pero $\\log 10 + \\log 10 = 2$."},
      {texto:"$\\log a \\cdot \\log b$", porque:"Tampoco: no existe esa propiedad."},
      {texto:"$\\dfrac{\\log a}{\\log b}$", porque:"Eso es el cambio de base, y no tiene nada que ver."}],
    porque:"Las propiedades sirven para productos y cocientes, nunca para sumas dentro del logaritmo." },

  { id:"log-07", tema:"mat-b-logaritmos", etiqueta:"Ecuaciones",
    enunciado:"Resuelve $3^x = 81$",
    opciones:[{texto:"$x = 4$", bien:true},
      {texto:"$x = 27$", porque:"Has dividido 81 entre 3."},
      {texto:"$x = 3$", porque:"$3^3 = 27$, no 81. Prueba con uno más."},
      {texto:"$x = 243$", porque:"Eso es $3^5$: te has pasado."}],
    porque:"$81 = 3^4$, así que con la misma base los exponentes son iguales: $x = 4$." },

  { id:"log-08", tema:"mat-b-logaritmos", etiqueta:"Ecuaciones",
    enunciado:"¿Cuándo hace falta usar logaritmos para resolver $a^x = b$?",
    opciones:[{texto:"Cuando $b$ no es una potencia exacta de $a$", bien:true},
      {texto:"Siempre", porque:"Si $b$ es potencia de $a$ basta igualar exponentes, que es más rápido."},
      {texto:"Nunca: siempre se puede a ojo", porque:"$2^x = 10$ no sale a ojo: la solución no es entera."},
      {texto:"Solo si $x$ es negativo", porque:"El signo de $x$ no tiene nada que ver."}],
    porque:"Si no puedes escribir los dos lados con la misma base, el logaritmo es la única forma de bajar la $x$ del exponente." },

  { id:"log-09", tema:"mat-b-logaritmos", etiqueta:"Base 10",
    enunciado:"$\\log 1000$ (logaritmo decimal) vale…",
    opciones:[{texto:"3", bien:true},
      {texto:"100", porque:"Has dividido entre 10."},
      {texto:"10", porque:"10 es la base, no el resultado."},
      {texto:"1", porque:"$\\log 10 = 1$; aquí hay tres ceros."}],
    porque:"Cuando no se escribe base, es 10. Y $10^3 = 1000$, así que vale 3." },

  { id:"log-10", tema:"mat-b-logaritmos", etiqueta:"Aplicación",
    enunciado:"El pH se calcula como $-\\log[\\text{H}^+]$. Si $[\\text{H}^+] = 10^{-4}$, el pH es…",
    opciones:[{texto:"4", bien:true},
      {texto:"$-4$", porque:"Falta el signo menos de delante de la fórmula: convierte el $-4$ en $+4$."},
      {texto:"0,0001", porque:"Ese es el valor de la concentración, no su logaritmo."},
      {texto:"10", porque:"10 es la base del logaritmo."}],
    porque:"$-\\log 10^{-4} = -(-4) = 4$. Ácido, porque es menor que 7." },

  { id:"log-11", tema:"mat-b-logaritmos", etiqueta:"Aplicación",
    enunciado:"Un terremoto de magnitud 7 comparado con uno de magnitud 5 libera…",
    opciones:[{texto:"100 veces más energía en amplitud", bien:true},
      {texto:"2 veces más", porque:"La escala Richter es logarítmica: cada punto multiplica por 10, no suma."},
      {texto:"1,4 veces más", porque:"Has dividido 7 entre 5. La escala no funciona así."},
      {texto:"20 veces más", porque:"Serían 10 × 10, no 10 + 10."}],
    porque:"Cada punto de la escala es un factor de 10, así que dos puntos son $10^2 = 100$ veces." },

  { id:"log-12", tema:"mat-b-logaritmos", etiqueta:"Relación con potencias",
    enunciado:"$\\log_5 5^7$ vale…",
    opciones:[{texto:"7", bien:true},
      {texto:"35", porque:"Has multiplicado 5 por 7."},
      {texto:"5", porque:"5 es la base."},
      {texto:"$5^7$", porque:"El logaritmo devuelve el exponente, no la potencia entera."}],
    porque:"El logaritmo y la potencia de la misma base se cancelan: $\\log_a a^n = n$." },

  { id:"log-13", tema:"mat-b-logaritmos", etiqueta:"Cambio de base",
    enunciado:"Para calcular $\\log_3 50$ con una calculadora que solo tiene log decimal…",
    opciones:[{texto:"$\\dfrac{\\log 50}{\\log 3}$", bien:true},
      {texto:"$\\log 50 - \\log 3$", porque:"Eso sería $\\log \\frac{50}{3}$, que es otra cosa."},
      {texto:"$\\log 50 \\cdot \\log 3$", porque:"No existe esa propiedad."},
      {texto:"$\\dfrac{\\log 3}{\\log 50}$", porque:"Está al revés: arriba va el argumento, abajo la base."}],
    porque:"Cambio de base: $\\log_a b = \\frac{\\log b}{\\log a}$. Arriba el argumento, abajo la base." },

  { id:"log-14", tema:"mat-b-logaritmos", etiqueta:"Problema",
    enunciado:"Inviertes 1.000 € al 5 % compuesto. ¿Qué hay que despejar para saber cuándo se duplican?",
    opciones:[{texto:"El exponente, y por eso hace falta un logaritmo", bien:true},
      {texto:"El capital inicial", porque:"Ese ya lo sabes: 1.000 €."},
      {texto:"El rédito", porque:"También lo sabes: el 5 %."},
      {texto:"Nada: se divide 2.000 entre 1.000", porque:"Eso da 2, que es cuántas veces crece, no cuántos años tarda."}],
    porque:"La ecuación es $1000 \\cdot 1{,}05^{\\,t} = 2000$, o sea $1{,}05^{\\,t} = 2$. La incógnita está en el exponente: logaritmo." }
);
