/* preguntas-elec.js — circuitos y electrónica.
   tec-11 a tec-14 ya cubren Ohm, serie/paralelo y potencia en preguntas-tec.js;
   estas amplían el tema. */
BANCO.push(
  { id:"elec-01", tema:"tec-electronica", etiqueta:"Magnitudes",
    enunciado:"La <b>intensidad</b> de corriente mide…",
    opciones:[{texto:"Cuántos electrones pasan por segundo", bien:true},
      {texto:"La fuerza con que empuja la pila", porque:"Eso es la tensión o voltaje."},
      {texto:"Lo que se opone al paso de la corriente", porque:"Eso es la resistencia."},
      {texto:"La energía consumida", porque:"Eso es la potencia por el tiempo."}],
    porque:"Intensidad (amperios) es caudal de carga. La analogía del agua: el voltaje es la presión, la intensidad el caudal y la resistencia lo estrecha que es la tubería." },

  { id:"elec-02", tema:"tec-electronica", etiqueta:"Ley de Ohm",
    enunciado:"Si en un circuito aumenta la resistencia y el voltaje no cambia, la intensidad…",
    opciones:[{texto:"Disminuye", bien:true},
      {texto:"Aumenta", porque:"Más resistencia significa más dificultad: pasa menos corriente."},
      {texto:"No cambia", porque:"I = V/R: si R sube y V se mantiene, I baja."},
      {texto:"Se vuelve negativa", porque:"La intensidad no se vuelve negativa por eso."}],
    porque:"I = V / R. Si el denominador crece y el numerador no, el resultado baja." },

  { id:"elec-03", tema:"tec-electronica", etiqueta:"Serie",
    enunciado:"Dos resistencias de 10 Ω y 20 Ω en serie equivalen a…",
    opciones:[{texto:"30 Ω", bien:true},
      {texto:"6,67 Ω", porque:"Ese sería el resultado en paralelo."},
      {texto:"200 Ω", porque:"Has multiplicado sin dividir."},
      {texto:"10 Ω", porque:"En serie la equivalente es mayor que cualquiera de las dos."}],
    porque:"En serie se suman. Y la comprobación: el resultado tiene que ser mayor que la mayor de ellas." },

  { id:"elec-04", tema:"tec-electronica", etiqueta:"Paralelo",
    enunciado:"Dos resistencias iguales de 20 Ω en paralelo equivalen a…",
    opciones:[{texto:"10 Ω", bien:true},
      {texto:"40 Ω", porque:"Eso sería en serie."},
      {texto:"20 Ω", porque:"En paralelo la equivalente siempre baja."},
      {texto:"400 Ω", porque:"Has multiplicado sin dividir entre la suma."}],
    porque:"Dos iguales en paralelo dan la mitad. Más caminos para la corriente, menos resistencia total." },

  { id:"elec-05", tema:"tec-electronica", etiqueta:"Comprobación",
    enunciado:"Calculas un paralelo y te sale una resistencia mayor que las dos originales. Eso significa…",
    opciones:[{texto:"Que te has equivocado", bien:true},
      {texto:"Que el circuito es especial", porque:"No hay excepciones: en paralelo siempre baja."},
      {texto:"Que hay que sumar también", porque:"Sumar es lo de serie."},
      {texto:"Que las resistencias están rotas", porque:"El error está en el cálculo, no en el material."}],
    porque:"En paralelo el resultado es siempre menor que la resistencia más pequeña. Es la comprobación más rápida que existe." },

  { id:"elec-06", tema:"tec-electronica", etiqueta:"Luces de casa",
    enunciado:"¿Por qué las bombillas de una casa se conectan en paralelo?",
    opciones:[{texto:"Para que cada una funcione independientemente y todas reciban 230 V", bien:true},
      {texto:"Porque gastan menos", porque:"El consumo depende de la potencia de cada una, no de la conexión."},
      {texto:"Porque es más barato de instalar", porque:"En realidad necesita más cable que en serie."},
      {texto:"Porque duran más", porque:"La duración depende de la bombilla."}],
    porque:"En serie, si se funde una se apagan todas y además cada una recibiría solo una parte del voltaje." },

  { id:"elec-07", tema:"tec-electronica", etiqueta:"Potencia",
    enunciado:"Un aparato de 2.000 W funcionando 3 horas consume…",
    opciones:[{texto:"6 kWh", bien:true},
      {texto:"6.000 kWh", porque:"Falta pasar de vatios a kilovatios: 2.000 W son 2 kW."},
      {texto:"2 kWh", porque:"Falta multiplicar por las 3 horas."},
      {texto:"667 W", porque:"Has dividido en vez de multiplicar."}],
    porque:"Energía = potencia × tiempo = 2 kW × 3 h = 6 kWh. Esa es la unidad que aparece en la factura." },

  { id:"elec-08", tema:"tec-electronica", etiqueta:"Código de colores",
    enunciado:"En el código de colores, el <b>tercer</b> anillo indica…",
    opciones:[{texto:"Por cuánto se multiplica (cuántos ceros se añaden)", bien:true},
      {texto:"La tercera cifra", porque:"En el código de cuatro bandas, las cifras son solo las dos primeras."},
      {texto:"La tolerancia", porque:"Esa es la cuarta banda, la que va separada."},
      {texto:"La potencia máxima", porque:"Eso no se indica con colores, sino con el tamaño."}],
    porque:"Dos cifras, un multiplicador y la tolerancia. Negro 0, marrón 1, rojo 2, naranja 3, amarillo 4…" },

  { id:"elec-09", tema:"tec-electronica", etiqueta:"Componentes",
    enunciado:"Un <b>diodo</b> sirve para…",
    opciones:[{texto:"Dejar pasar la corriente en un solo sentido", bien:true},
      {texto:"Aumentar la resistencia", porque:"Eso lo hace una resistencia."},
      {texto:"Almacenar carga", porque:"Eso lo hace un condensador."},
      {texto:"Medir el voltaje", porque:"Eso lo hace un voltímetro."}],
    porque:"Es una válvula para la electricidad. Un LED es un diodo que además emite luz al pasar la corriente." },

  { id:"elec-10", tema:"tec-electronica", etiqueta:"LED",
    enunciado:"¿Por qué un LED necesita una resistencia en serie?",
    opciones:[{texto:"Para limitar la corriente y que no se queme", bien:true},
      {texto:"Para que brille más", porque:"Al revés: la resistencia baja algo el brillo, pero lo mantiene vivo."},
      {texto:"Para darle color", porque:"El color depende del material del LED."},
      {texto:"No la necesita", porque:"Sin ella, el LED se destruye en segundos."}],
    porque:"El LED apenas ofrece resistencia: sin limitarla, la corriente se dispara y lo quema. Es el error número uno al montar circuitos." },

  { id:"elec-11", tema:"tec-electronica", etiqueta:"Medir",
    enunciado:"El <b>amperímetro</b> se conecta…",
    opciones:[{texto:"En serie, intercalado en el circuito", bien:true},
      {texto:"En paralelo con el componente", porque:"Así se conecta el voltímetro, no el amperímetro."},
      {texto:"Da igual cómo", porque:"Conectarlo mal puede provocar un cortocircuito."},
      {texto:"Solo con el circuito apagado", porque:"Mide corriente: tiene que estar encendido."}],
    porque:"Para medir el caudal hay que ponerse en el camino. El voltímetro, en cambio, va en paralelo, porque mide diferencia entre dos puntos." },

  { id:"elec-12", tema:"tec-electronica", etiqueta:"Seguridad",
    enunciado:"¿Qué es un cortocircuito?",
    opciones:[{texto:"Un camino de resistencia casi nula que dispara la intensidad", bien:true},
      {texto:"Un circuito demasiado corto", porque:"No tiene que ver con la longitud del cable."},
      {texto:"Un circuito sin pila", porque:"Sin pila no pasa corriente."},
      {texto:"Un circuito en paralelo", porque:"El paralelo es una conexión normal y segura."}],
    porque:"Si R tiende a cero, I = V/R se dispara: calor, humo y fuego. Para eso están los fusibles y los diferenciales." },

  { id:"elec-13", tema:"tec-electronica", etiqueta:"Analogía",
    enunciado:"En la analogía del agua, el <b>voltaje</b> equivale a…",
    opciones:[{texto:"La presión", bien:true},
      {texto:"El caudal", porque:"El caudal es la intensidad."},
      {texto:"El grosor de la tubería", porque:"Eso es la resistencia."},
      {texto:"La cantidad de agua", porque:"Eso sería la carga total."}],
    porque:"Presión (V), caudal (I) y estrechez de la tubería (R). Más presión o tubería más ancha, más caudal: eso es la ley de Ohm." },

  { id:"elec-14", tema:"tec-electronica", etiqueta:"Problema",
    enunciado:"Con una pila de 9 V y una resistencia de 3 Ω, ¿qué intensidad circula y qué potencia se disipa?",
    opciones:[{texto:"3 A y 27 W", bien:true},
      {texto:"27 A y 3 W", porque:"Están cambiados: I = V/R = 3 A, y P = V·I = 27 W."},
      {texto:"3 A y 9 W", porque:"La potencia es V·I = 9 × 3 = 27 W."},
      {texto:"0,33 A y 3 W", porque:"Has dividido al revés: es V entre R, no R entre V."}],
    porque:"I = 9/3 = 3 A. P = V · I = 9 × 3 = 27 W." }
);
