/* preguntas-poli.js — polinomios y factorización. */
BANCO.push(
  { id:"poli-01", tema:"mat-b-polinomios", etiqueta:"Grado",
    enunciado:"¿Cuál es el grado de $P(x) = 5x^3 - 2x^7 + x$?",
    opciones:[{texto:"7", bien:true},
      {texto:"3", porque:"El 3 es el exponente del primer término, pero el grado es el mayor de todos."},
      {texto:"11", porque:"Los exponentes no se suman: el grado es el mayor."},
      {texto:"1", porque:"Ese es el grado del último término."}],
    porque:"El grado es el exponente más alto que aparece, esté donde esté escrito." },

  { id:"poli-02", tema:"mat-b-polinomios", etiqueta:"Teorema del resto",
    enunciado:"Para saber el resto de dividir $P(x)$ entre $(x-3)$, lo más rápido es…",
    opciones:[{texto:"Calcular $P(3)$", bien:true},
      {texto:"Calcular $P(-3)$", porque:"El signo se cambia: si divides entre (x−3), el valor es +3."},
      {texto:"Hacer la división entera", porque:"Funciona, pero el teorema del resto lo da en un paso."},
      {texto:"Dividir el término independiente entre 3", porque:"No existe esa regla."}],
    porque:"Teorema del resto: el resto de dividir entre $(x-a)$ es $P(a)$. Un cálculo en vez de una división." },

  { id:"poli-03", tema:"mat-b-polinomios", etiqueta:"Raíces",
    enunciado:"Si $P(2) = 0$, entonces…",
    opciones:[{texto:"$(x-2)$ es un factor de $P(x)$", bien:true},
      {texto:"$(x+2)$ es un factor", porque:"El signo se invierte: si la raíz es 2, el factor es (x−2)."},
      {texto:"$P(x)$ no tiene raíces", porque:"Justo al revés: acabas de encontrar una."},
      {texto:"El grado de $P$ es 2", porque:"El valor de la raíz no dice nada del grado."}],
    porque:"Teorema del factor: si $a$ es raíz, $(x-a)$ divide al polinomio exactamente. Es la base de la factorización." },

  { id:"poli-04", tema:"mat-b-polinomios", etiqueta:"Ruffini",
    enunciado:"Al dividir por Ruffini entre $(x+3)$, el número que se usa en la caja es…",
    opciones:[{texto:"−3", bien:true},
      {texto:"3", porque:"Hay que cambiarle el signo: $(x+3)$ es $(x-(-3))$."},
      {texto:"El primer coeficiente", porque:"Ese se baja tal cual, pero no es el número de la caja."},
      {texto:"El término independiente", porque:"Ese entra en la cuenta al final, no como divisor."}],
    porque:"Ruffini divide entre $(x-a)$. Para $(x+3)$, $a$ vale $-3$." },

  { id:"poli-05", tema:"mat-b-polinomios", etiqueta:"Ruffini",
    enunciado:"Al hacer Ruffini, ¿qué significa que el último número salga 0?",
    opciones:[{texto:"Que la división es exacta y ese valor es una raíz", bien:true},
      {texto:"Que te has equivocado", porque:"Al contrario: es lo que buscas."},
      {texto:"Que el polinomio es cero", porque:"El polinomio no es cero, solo se anula en ese valor."},
      {texto:"Que no se puede dividir", porque:"Sí se puede, y además sale redondo."}],
    porque:"El último número de Ruffini es el resto. Cero significa división exacta y raíz encontrada." },

  { id:"poli-06", tema:"mat-b-polinomios", etiqueta:"Raíces enteras",
    enunciado:"Para buscar raíces enteras de $x^3 - 2x^2 - 5x + 6$, ¿qué valores conviene probar?",
    opciones:[{texto:"Los divisores de 6: ±1, ±2, ±3, ±6", bien:true},
      {texto:"Cualquier número, al azar", porque:"Hay un atajo: solo los divisores del término independiente pueden ser raíces enteras."},
      {texto:"Solo números positivos", porque:"También hay que probar los negativos."},
      {texto:"Los divisores de 2, que es el coeficiente", porque:"El que manda es el término independiente, no el del medio."}],
    porque:"Una raíz entera tiene que dividir al término independiente. Eso reduce la búsqueda a unos pocos números." },

  { id:"poli-07", tema:"mat-b-polinomios", etiqueta:"Identidades",
    enunciado:"$x^2 - 49$ factorizado es…",
    opciones:[{texto:"$(x+7)(x-7)$", bien:true},
      {texto:"$(x-7)^2$", porque:"Ese sería $x^2 - 14x + 49$: tiene término del medio."},
      {texto:"$(x+7)^2$", porque:"Ese sería $x^2 + 14x + 49$."},
      {texto:"No se puede factorizar", porque:"Sí: es una diferencia de cuadrados."}],
    porque:"Diferencia de cuadrados: $a^2 - b^2 = (a+b)(a-b)$. Aquí $49 = 7^2$." },

  { id:"poli-08", tema:"mat-b-polinomios", etiqueta:"Identidades",
    enunciado:"¿Se puede factorizar $x^2 + 25$?",
    opciones:[{texto:"No, con números reales no", bien:true},
      {texto:"Sí: $(x+5)(x-5)$", porque:"Eso es $x^2 - 25$, con menos. La suma de cuadrados no se factoriza."},
      {texto:"Sí: $(x+5)^2$", porque:"Eso da $x^2 + 10x + 25$: sobra el término del medio."},
      {texto:"Sí: $(x+25)(x+1)$", porque:"Al multiplicar eso sale $x^2 + 26x + 25$."}],
    porque:"Solo la DIFERENCIA de cuadrados se factoriza. La suma no tiene raíces reales: nunca vale cero." },

  { id:"poli-09", tema:"mat-b-polinomios", etiqueta:"Factor común",
    enunciado:"Lo primero que hay que intentar al factorizar es…",
    opciones:[{texto:"Sacar factor común", bien:true},
      {texto:"Aplicar Ruffini", porque:"Ruffini viene después: primero se simplifica lo evidente."},
      {texto:"Usar la fórmula de segundo grado", porque:"Solo sirve para grado 2, y aun así conviene mirar antes el factor común."},
      {texto:"Dividir entre x", porque:"Dividir cambia el polinomio; sacar factor común, no."}],
    porque:"Sacar factor común simplifica el problema y a veces lo resuelve entero. Es siempre el primer paso." },

  { id:"poli-10", tema:"mat-b-polinomios", etiqueta:"Trinomio",
    enunciado:"$x^2 - 7x + 12$ factorizado es…",
    opciones:[{texto:"$(x-3)(x-4)$", bien:true},
      {texto:"$(x+3)(x+4)$", porque:"Al multiplicar da $x^2 + 7x + 12$: el término del medio saldría positivo."},
      {texto:"$(x-6)(x-2)$", porque:"Multiplicados dan 12, pero sumados dan 8, no 7."},
      {texto:"$(x-12)(x+1)$", porque:"Suman −11, no −7."}],
    porque:"Dos números que multiplicados den 12 y sumados 7: el 3 y el 4. Con los dos signos negativos." },

  { id:"poli-11", tema:"mat-b-polinomios", etiqueta:"Fracciones algebraicas",
    enunciado:"Para simplificar $\\dfrac{x^2-9}{x-3}$ lo correcto es…",
    opciones:[{texto:"Factorizar arriba y cancelar: queda $x+3$", bien:true},
      {texto:"Cancelar las x directamente", porque:"No se pueden tachar términos sueltos de una suma: solo factores enteros."},
      {texto:"Cancelar el 9 con el 3", porque:"Mismo error: son términos, no factores."},
      {texto:"No se puede simplificar", porque:"Sí: arriba hay una diferencia de cuadrados."}],
    porque:"$x^2-9 = (x+3)(x-3)$, y ese $(x-3)$ se cancela con el de abajo. Solo se cancelan factores, nunca sumandos." },

  { id:"poli-12", tema:"mat-b-polinomios", etiqueta:"Error típico",
    enunciado:"¿Por qué está MAL simplificar $\\dfrac{x+5}{x}$ tachando las x?",
    opciones:[{texto:"Porque la x de arriba está sumando, no multiplicando", bien:true},
      {texto:"Porque falta un paréntesis", porque:"No es cuestión de paréntesis: es que no se puede cancelar un sumando."},
      {texto:"Porque x podría ser negativa", porque:"El signo no es el problema."},
      {texto:"No está mal", porque:"Sí lo está. Prueba con x=5: da 2, y si tachas saldría 6."}],
    porque:"Solo se cancelan factores que multiplican a todo. Compruébalo con números: con x=5 la fracción vale 2, no 6." },

  { id:"poli-13", tema:"mat-b-polinomios", etiqueta:"Estrategia",
    enunciado:"¿Cuántas raíces como mucho puede tener un polinomio de grado 3?",
    opciones:[{texto:"Tres", bien:true},
      {texto:"Una", porque:"Puede tener una, pero también dos o tres."},
      {texto:"Infinitas", porque:"Si tuviera infinitas raíces sería el polinomio cero."},
      {texto:"Seis", porque:"No puede pasar del grado."}],
    porque:"Un polinomio de grado n tiene como mucho n raíces. Por eso al factorizar salen a lo sumo n factores." },

  { id:"poli-14", tema:"mat-b-polinomios", etiqueta:"Problema",
    enunciado:"Factoriza del todo $x^3 - 4x$:",
    opciones:[{texto:"$x(x+2)(x-2)$", bien:true},
      {texto:"$x(x^2-4)$", porque:"Vas por buen camino pero no has acabado: $x^2-4$ todavía se factoriza."},
      {texto:"$(x-2)(x+2)$", porque:"Te has dejado la $x$ que sacaste como factor común."},
      {texto:"$x^2(x-4)$", porque:"Al multiplicar eso sale $x^3 - 4x^2$, que no es lo mismo."}],
    porque:"Primero factor común ($x$), y luego lo que queda es diferencia de cuadrados. Hay que factorizar hasta el final." }
);
