/* preguntas-textos.js — tipos de texto, conectores y comentario. */
BANCO.push(
  { id:"txt-01", tema:"len-textos", etiqueta:"Tipologías",
    enunciado:"Un texto que dice cómo es un paisaje, sin que pase nada, es…",
    opciones:[{texto:"Descriptivo", bien:true},
      {texto:"Narrativo", porque:"En el narrativo los hechos avanzan en el tiempo; aquí no pasa nada."},
      {texto:"Expositivo", porque:"El expositivo informa sobre un tema; describir no es lo mismo que explicar."},
      {texto:"Argumentativo", porque:"No defiende ninguna postura."}],
    porque:"Describir es pintar con palabras: predominan los adjetivos y los verbos de estado." },

  { id:"txt-02", tema:"len-textos", etiqueta:"Tipologías",
    enunciado:"¿Cuál es la diferencia entre expositivo y argumentativo?",
    opciones:[{texto:"El expositivo informa; el argumentativo defiende una postura", bien:true},
      {texto:"El expositivo es más largo", porque:"La longitud no distingue nada."},
      {texto:"El argumentativo es literario", porque:"Puede ser de cualquier ámbito: prensa, ciencia, publicidad."},
      {texto:"Son lo mismo", porque:"Uno es neutro y el otro toma partido: se nota en el vocabulario."}],
    porque:"El expositivo busca que entiendas; el argumentativo, que estés de acuerdo. Muchos textos reales mezclan los dos." },

  { id:"txt-03", tema:"len-textos", etiqueta:"Tesis",
    enunciado:"La tesis de un texto argumentativo es…",
    opciones:[{texto:"La idea que el autor quiere que aceptes", bien:true},
      {texto:"El tema del que habla", porque:"El tema es de qué trata; la tesis es qué opina sobre ello."},
      {texto:"El primer párrafo", porque:"Puede estar al principio, al final o incluso implícita."},
      {texto:"El resumen final", porque:"La conclusión puede repetirla, pero no es lo mismo."}],
    porque:"Tema: los móviles en clase. Tesis: deberían prohibirse. El tema es neutro; la tesis toma partido." },

  { id:"txt-04", tema:"len-textos", etiqueta:"Estructura",
    enunciado:"En una estructura <b>inductiva</b>, la tesis…",
    opciones:[{texto:"Aparece al final, después de los argumentos", bien:true},
      {texto:"Aparece al principio", porque:"Eso es la estructura deductiva."},
      {texto:"No aparece", porque:"Aparece, pero al final."},
      {texto:"Aparece dos veces", porque:"Eso sería una estructura encuadrada."}],
    porque:"Inductiva: de los datos a la conclusión. Deductiva: la tesis primero y luego las pruebas. Encuadrada: al principio y repetida al final." },

  { id:"txt-05", tema:"len-textos", etiqueta:"Argumentos",
    enunciado:"«Según la OMS, hay que reducir la sal» es un argumento de…",
    opciones:[{texto:"Autoridad", bien:true},
      {texto:"Datos", porque:"No hay cifras: hay una fuente reconocida."},
      {texto:"Ejemplo", porque:"No cuenta un caso concreto."},
      {texto:"Analogía", porque:"No compara con nada."}],
    porque:"Se apoya en alguien reconocido. Es fuerte si la fuente es fiable, y débil si la autoridad no viene al caso." },

  { id:"txt-06", tema:"len-textos", etiqueta:"Argumentos",
    enunciado:"¿Cuál es el punto débil de un argumento basado en un solo ejemplo?",
    opciones:[{texto:"Un caso aislado no demuestra una regla general", bien:true},
      {texto:"Los ejemplos no son argumentos", porque:"Sí lo son, y muy útiles: el problema es generalizar desde uno solo."},
      {texto:"Son difíciles de entender", porque:"Al contrario: son los más claros."},
      {texto:"No se pueden usar por escrito", porque:"Se usan constantemente."}],
    porque:"«Mi primo dejó el azúcar y adelgazó» no prueba que funcione para todos. Los ejemplos ilustran; los datos demuestran." },

  { id:"txt-07", tema:"len-textos", etiqueta:"Conectores",
    enunciado:"«Estudió mucho; ____, suspendió.» ¿Qué conector va?",
    opciones:[{texto:"sin embargo", bien:true},
      {texto:"por lo tanto", porque:"Eso indicaría consecuencia, y suspender no es consecuencia de estudiar mucho."},
      {texto:"además", porque:"«Además» suma en la misma dirección, y aquí hay contraste."},
      {texto:"porque", porque:"Introduce una causa, no una oposición."}],
    porque:"Las dos ideas chocan: hace falta un conector de oposición. También valdrían «no obstante» o «en cambio»." },

  { id:"txt-08", tema:"len-textos", etiqueta:"Coherencia",
    enunciado:"Un texto es <b>coherente</b> cuando…",
    opciones:[{texto:"Todo lo que dice tiene relación con el tema y no se contradice", bien:true},
      {texto:"Usa muchos conectores", porque:"Eso es cohesión, y se pueden usar conectores sin que el texto tenga sentido."},
      {texto:"No tiene faltas", porque:"La ortografía es otra cosa."},
      {texto:"Es largo", porque:"La longitud no aporta coherencia."}],
    porque:"Coherencia es el sentido global: de qué habla y si encaja. Cohesión son los enlaces entre frases." },

  { id:"txt-09", tema:"len-textos", etiqueta:"Cohesión",
    enunciado:"«Ana llegó. Ana abrió la puerta. Ana se sentó.» ¿Qué falla?",
    opciones:[{texto:"Falta cohesión: se repite el sujeto en vez de omitirlo", bien:true},
      {texto:"Falta coherencia", porque:"Se entiende perfectamente y todo habla de lo mismo: el problema es cómo está enlazado."},
      {texto:"Nada, está bien", porque:"Repetir el nombre tres veces suena a máquina."},
      {texto:"Faltan adjetivos", porque:"No es cuestión de adornar."}],
    porque:"En español el sujeto se omite cuando se sobreentiende: «Ana llegó, abrió la puerta y se sentó»." },

  { id:"txt-10", tema:"len-textos", etiqueta:"Resumen",
    enunciado:"¿Qué NO debe tener un buen resumen?",
    opciones:[{texto:"Tu opinión sobre el texto", bien:true},
      {texto:"Las ideas principales", porque:"Son justo lo que debe llevar."},
      {texto:"Tus propias palabras", porque:"Hay que reformular, no copiar."},
      {texto:"Un orden lógico", porque:"Debe tenerlo."}],
    porque:"El resumen recoge lo que dice el texto, no lo que te parece. La opinión va en el comentario crítico, que es otra parte." },

  { id:"txt-11", tema:"len-textos", etiqueta:"Comentario",
    enunciado:"Al comentar un texto, ¿qué se hace primero?",
    opciones:[{texto:"Leerlo entero un par de veces y localizar el tema", bien:true},
      {texto:"Empezar a escribir la opinión", porque:"Sin saber qué dice el texto, la opinión va a ir suelta."},
      {texto:"Contar las palabras", porque:"No aporta nada."},
      {texto:"Buscar las figuras literarias", porque:"Eso viene después, y solo si el texto es literario."}],
    porque:"El orden: leer, tema, estructura, resumen, tipo de texto, recursos y por último la valoración." },

  { id:"txt-12", tema:"len-textos", etiqueta:"Registro",
    enunciado:"«Se ruega a los usuarios que se abstengan de fumar» está en registro…",
    opciones:[{texto:"Formal", bien:true},
      {texto:"Coloquial", porque:"Lo coloquial sería «no fuméis aquí»."},
      {texto:"Vulgar", porque:"No hay incorrecciones ni tacos."},
      {texto:"Literario", porque:"No busca belleza: es un aviso."}],
    porque:"Pasiva refleja, impersonalidad y léxico culto: marcas típicas del registro formal." },

  { id:"txt-13", tema:"len-textos", etiqueta:"Objetividad",
    enunciado:"¿Cuál de estas frases es más objetiva?",
    opciones:[{texto:"El paro bajó un 2 % en el último trimestre", bien:true},
      {texto:"Afortunadamente el paro bajó algo", porque:"«Afortunadamente» y «algo» son valoraciones del que escribe."},
      {texto:"El paro bajó una miseria", porque:"«Una miseria» es claramente subjetivo."},
      {texto:"Por fin bajó el paro", porque:"«Por fin» expresa alivio: subjetivo."}],
    porque:"Objetivo: dato verificable y sin valoración. Los adverbios y adjetivos valorativos delatan la subjetividad." },

  { id:"txt-14", tema:"len-textos", etiqueta:"Problema",
    enunciado:"Un artículo de opinión que empieza «Los datos son claros: el 40 % de los jóvenes...» usa una estructura…",
    opciones:[{texto:"Inductiva: de los datos hacia la conclusión", bien:true},
      {texto:"Deductiva", porque:"En la deductiva la tesis va primero, y aquí empieza por las pruebas."},
      {texto:"Narrativa", porque:"No cuenta hechos en el tiempo."},
      {texto:"Circular", porque:"Esa sería la encuadrada, con la tesis al principio y al final."}],
    porque:"Empieza con la prueba y va llevando al lector hacia la tesis, que llegará después. Eso es inducción." }
);
