/* preguntas-lengua.js — banco de Lengua. */
BANCO.push(
  { id:"sint-01", tema:"len-oracion-simple", etiqueta:"Sujeto",
    enunciado:"En «Ayer llegaron tus primos», el sujeto es…",
    opciones:[{texto:"tus primos", bien:true},
      {texto:"Ayer", porque:"«Ayer» dice cuándo: es circunstancial de tiempo. Que vaya primero no lo hace sujeto."},
      {texto:"llegaron", porque:"Ese es el verbo."},
      {texto:"No tiene sujeto", porque:"Sí tiene: pon el verbo en singular y verás que cambia «tus primos» a «tu primo»."}],
    porque:"El sujeto concuerda con el verbo: si cambias «llegaron» por «llegó», tiene que cambiar «tus primos». Y no va siempre delante." },

  { id:"sint-02", tema:"len-oracion-simple", etiqueta:"Sujeto",
    enunciado:"¿Cuál de estas oraciones es impersonal (sin sujeto)?",
    opciones:[{texto:"Hay mucha gente en la plaza", bien:true},
      {texto:"Vinieron muchos amigos", porque:"El sujeto es «muchos amigos»: concuerda con «vinieron»."},
      {texto:"Se vendieron las entradas", porque:"Ahí «las entradas» es sujeto: es una pasiva refleja, no impersonal."},
      {texto:"Llegó tarde", porque:"Tiene sujeto elíptico: él o ella. Se sobreentiende, pero existe."}],
    porque:"Con «haber» impersonal no hay sujeto: «mucha gente» es complemento directo. Prueba: «Hay muchas personas» no cambia el verbo a «Han»." },

  { id:"sint-03", tema:"len-oracion-simple", etiqueta:"CD",
    enunciado:"La prueba más fiable para saber si algo es complemento directo es…",
    opciones:[{texto:"Sustituirlo por lo, la, los o las", bien:true},
      {texto:"Preguntar «¿qué?» al verbo", porque:"Funciona a veces, pero falla: en «Trabajo mucho», «mucho» responde a «¿qué?» y es circunstancial."},
      {texto:"Ver si lleva la preposición «a»", porque:"El CD de persona lleva «a» (vi a Marta), y el CI también. No sirve para distinguir."},
      {texto:"Ver si va justo detrás del verbo", porque:"La posición no decide nada en español: el orden es muy libre."}],
    porque:"Si se puede sustituir por lo/la/los/las, es CD. «Compró el libro» → «Lo compró»." },

  { id:"sint-04", tema:"len-oracion-simple", etiqueta:"CI",
    enunciado:"En «Le escribí una carta a mi abuela», el complemento indirecto es…",
    opciones:[{texto:"a mi abuela (y el «le» que lo duplica)", bien:true},
      {texto:"una carta", porque:"Eso es el CD: «la escribí»."},
      {texto:"Le", porque:"«Le» es el CI, sí, pero duplicado: se refiere a «a mi abuela». Los dos son la misma función."},
      {texto:"escribí", porque:"Ese es el verbo."}],
    porque:"El CI se sustituye por «le/les», y aquí ya aparece duplicado, que es lo normal en español." },

  { id:"sint-05", tema:"len-oracion-simple", etiqueta:"CD vs CI",
    enunciado:"En «Vi a Marta en el cine», «a Marta» es…",
    opciones:[{texto:"Complemento directo", bien:true},
      {texto:"Complemento indirecto", porque:"La «a» despista, pero prueba a sustituir: «La vi». Con «le» no funcionaría igual."},
      {texto:"Circunstancial", porque:"No se puede quitar: «Vi en el cine» queda coja."},
      {texto:"Sujeto", porque:"El sujeto es «yo», que va elíptico."}],
    porque:"El CD de persona lleva «a», pero sigue siendo CD: se sustituye por «la»." },

  { id:"sint-06", tema:"len-oracion-simple", etiqueta:"CC",
    enunciado:"¿Cuántos complementos circunstanciales hay en «Ayer estudié en la biblioteca con mi hermano»?",
    opciones:[{texto:"Tres", bien:true},
      {texto:"Uno", porque:"Hay tres: de tiempo, de lugar y de compañía."},
      {texto:"Dos", porque:"Te has dejado uno: cuenta «ayer», «en la biblioteca» y «con mi hermano»."},
      {texto:"Ninguno", porque:"Los tres se pueden quitar y la oración sigue en pie: son circunstanciales."}],
    porque:"«Ayer» (tiempo), «en la biblioteca» (lugar) y «con mi hermano» (compañía). Se pueden quitar todos." },

  { id:"sint-07", tema:"len-oracion-simple", etiqueta:"Atributo",
    enunciado:"El predicado es NOMINAL cuando el verbo es…",
    opciones:[{texto:"Ser, estar o parecer", bien:true},
      {texto:"Cualquier verbo con complemento directo", porque:"Eso es predicado verbal: el CD no es atributo."},
      {texto:"Un verbo en pasado", porque:"El tiempo verbal no tiene nada que ver con esto."},
      {texto:"Un verbo sin sujeto", porque:"Eso sería una impersonal, que es otra cosa."}],
    porque:"Ser, estar y parecer son copulativos: no dicen una acción, unen el sujeto con su atributo." },

  { id:"sint-08", tema:"len-oracion-simple", etiqueta:"Atributo",
    enunciado:"En «Mi hermana está cansada», «cansada» es…",
    opciones:[{texto:"Atributo", bien:true},
      {texto:"Complemento directo", porque:"Con verbos copulativos no hay CD. Y se sustituye por «lo»: «Mi hermana lo está»."},
      {texto:"Complemento predicativo", porque:"El predicativo va con verbos NO copulativos: «Llegó cansada»."},
      {texto:"Circunstancial de modo", porque:"No se puede quitar: «Mi hermana está» no significa lo mismo."}],
    porque:"Con «estar», lo que sigue es atributo, y se sustituye siempre por «lo»." },

  { id:"sint-09", tema:"len-oracion-simple", etiqueta:"Predicativo",
    enunciado:"En «Los niños llegaron cansados», «cansados» es…",
    opciones:[{texto:"Complemento predicativo", bien:true},
      {texto:"Atributo", porque:"Sería atributo si el verbo fuera copulativo, y «llegar» no lo es."},
      {texto:"Complemento directo", porque:"No se puede sustituir por «los»: «Los niños los llegaron» no significa nada."},
      {texto:"Circunstancial", porque:"Concuerda en género y número con el sujeto, y un circunstancial no hace eso."}],
    porque:"Es predicativo: complementa a la vez al verbo y al sujeto, y concuerda con él (niños cansados, niñas cansadas)." },

  { id:"sint-10", tema:"len-oracion-simple", etiqueta:"Suplemento",
    enunciado:"En «Hablamos de política», «de política» es…",
    opciones:[{texto:"Suplemento (complemento de régimen)", bien:true},
      {texto:"Complemento directo", porque:"El CD no lleva preposición fija y se sustituye por «lo». Aquí no se puede: «Lo hablamos» es otra cosa."},
      {texto:"Circunstancial", porque:"No se puede quitar: «Hablamos» solo queda incompleta. Además la preposición la exige el verbo."},
      {texto:"Complemento indirecto", porque:"El CI va con «a» y se sustituye por «le»."}],
    porque:"Hay verbos que exigen una preposición concreta: hablar DE, acordarse DE, confiar EN. Eso es el suplemento." },

  { id:"sint-11", tema:"len-oracion-simple", etiqueta:"Pasiva",
    enunciado:"Al pasar «El jurado premió la novela» a pasiva, «la novela» pasa a ser…",
    opciones:[{texto:"Sujeto: «La novela fue premiada por el jurado»", bien:true},
      {texto:"Complemento agente", porque:"El agente es quien hace la acción: «por el jurado»."},
      {texto:"Sigue siendo CD", porque:"En la pasiva el CD asciende a sujeto: es justo la prueba de que era CD."},
      {texto:"Complemento indirecto", porque:"No: el CI no puede ser sujeto de la pasiva."}],
    porque:"Solo el CD puede convertirse en sujeto de la pasiva. Es una de las pruebas para reconocerlo." },

  { id:"sint-12", tema:"len-oracion-simple", etiqueta:"Método",
    enunciado:"¿Por dónde conviene empezar a analizar una oración?",
    opciones:[{texto:"Por el verbo", bien:true},
      {texto:"Por la primera palabra", porque:"La posición engaña: la oración puede empezar por un circunstancial."},
      {texto:"Por el sujeto", porque:"Para encontrar el sujeto ya necesitas el verbo: es el que concuerda con él."},
      {texto:"Por los complementos", porque:"Sin saber cuál es el verbo no puedes saber qué complementa cada cosa."}],
    porque:"El verbo es el centro: primero lo localizas, luego preguntas «¿quién?» para el sujeto, y lo que queda son complementos." },

  { id:"sint-13", tema:"len-oracion-simple", etiqueta:"Sujeto",
    enunciado:"En «Me gustan las matemáticas», el sujeto es…",
    opciones:[{texto:"las matemáticas", bien:true},
      {texto:"Me", porque:"«Me» es complemento indirecto: a mí me gustan. Es el error más repetido con el verbo gustar."},
      {texto:"gustan", porque:"Ese es el verbo."},
      {texto:"Yo, elíptico", porque:"Si fuera «yo», el verbo iría en singular: «gusto»."}],
    porque:"El verbo está en plural porque concuerda con «las matemáticas». Literalmente: las matemáticas me gustan a mí." },

  { id:"sint-14", tema:"len-oracion-simple", etiqueta:"Problema",
    enunciado:"«El profesor entregó los exámenes a los alumnos en clase». ¿Qué función tiene «a los alumnos»?",
    opciones:[{texto:"Complemento indirecto", bien:true},
      {texto:"Complemento directo", porque:"El CD es «los exámenes»: «los entregó». «A los alumnos» se sustituye por «les»."},
      {texto:"Circunstancial", porque:"Se puede quitar, sí, pero se sustituye por «les», y eso lo delata como CI."},
      {texto:"Sujeto", porque:"El sujeto es «el profesor»."}],
    porque:"«Les entregó los exámenes»: la sustitución por «les» es la prueba del complemento indirecto." }
);
