/* preguntas-robot.js — banco de robótica y sistemas de control. */
BANCO.push(
  { id:"rob-01", tema:"tec-robotica", etiqueta:"Sistema de control",
    enunciado:"Las tres partes de cualquier sistema de control son…",
    opciones:[{texto:"Entrada, proceso y salida", bien:true},
      {texto:"Pila, cables y motor", porque:"Eso son componentes concretos, no las partes del sistema."},
      {texto:"Hardware, software y usuario", porque:"El usuario no es una parte del sistema de control."},
      {texto:"Sensor, actuador y pantalla", porque:"La pantalla es un actuador más; falta el proceso, que decide."}],
    porque:"Entrada: sensores que recogen información. Proceso: el controlador que decide. Salida: actuadores que actúan." },

  { id:"rob-02", tema:"tec-robotica", etiqueta:"Sensores",
    enunciado:"¿Cuál de estos es un sensor?",
    opciones:[{texto:"Una LDR", bien:true},
      {texto:"Un motor", porque:"El motor actúa: convierte electricidad en movimiento. Es actuador."},
      {texto:"Un LED", porque:"El LED da luz: es salida."},
      {texto:"Un zumbador", porque:"Produce sonido: salida."}],
    porque:"La LDR cambia su resistencia con la luz: mide algo del entorno. Eso es un sensor." },

  { id:"rob-03", tema:"tec-robotica", etiqueta:"Lazo",
    enunciado:"Un sistema de lazo cerrado se distingue porque…",
    opciones:[{texto:"Mide el resultado y corrige (realimentación)", bien:true},
      {texto:"Está dentro de una caja cerrada", porque:"«Cerrado» se refiere al lazo de información, no a la carcasa."},
      {texto:"No necesita energía", porque:"Todos los sistemas de control necesitan energía."},
      {texto:"Es más barato", porque:"Suele ser más caro, porque necesita sensores."}],
    porque:"En lazo cerrado la salida se mide y esa información vuelve a la entrada. Un termostato es el ejemplo de libro." },

  { id:"rob-04", tema:"tec-robotica", etiqueta:"Lazo",
    enunciado:"Una tostadora con temporizador que no comprueba el pan es un sistema…",
    opciones:[{texto:"De lazo abierto", bien:true},
      {texto:"De lazo cerrado", porque:"Para serlo tendría que medir cómo está el pan y parar cuando esté tostado."},
      {texto:"Sin control", porque:"Sí tiene control: el temporizador decide cuándo parar."},
      {texto:"Robótico", porque:"No es un robot: no percibe su entorno."}],
    porque:"Hace lo programado sin mirar el resultado: lazo abierto." },

  { id:"rob-05", tema:"tec-robotica", etiqueta:"Arduino",
    enunciado:"¿Qué hace pinMode(13, OUTPUT)?",
    opciones:[{texto:"Configura el pin 13 como salida", bien:true},
      {texto:"Enciende el pin 13", porque:"Solo lo configura. Para encenderlo, digitalWrite(13, HIGH)."},
      {texto:"Lee el pin 13", porque:"Para leer se usa digitalRead o analogRead, y el pin sería INPUT."},
      {texto:"Espera 13 milisegundos", porque:"Eso sería delay(13)."}],
    porque:"pinMode prepara el pin: OUTPUT si va a mandar corriente (LED, motor), INPUT si va a recibir (pulsador)." },

  { id:"rob-06", tema:"tec-robotica", etiqueta:"Arduino",
    enunciado:"¿Cuánto espera delay(1500)?",
    opciones:[{texto:"1,5 segundos", bien:true},
      {texto:"1500 segundos", porque:"delay cuenta en milisegundos, no en segundos: serían 25 minutos."},
      {texto:"15 segundos", porque:"1500 ms son 1,5 s."},
      {texto:"0,15 segundos", porque:"Eso serían 150 ms."}],
    porque:"delay usa milisegundos: 1000 ms = 1 s, así que 1500 ms = 1,5 s." },

  { id:"rob-07", tema:"tec-robotica", etiqueta:"Arduino",
    enunciado:"¿Qué diferencia hay entre setup() y loop()?",
    opciones:[{texto:"setup se ejecuta una vez; loop se repite sin parar", bien:true},
      {texto:"setup es para sensores y loop para actuadores", porque:"Ambos pueden usar cualquier componente. La diferencia es cuántas veces se ejecutan."},
      {texto:"loop se ejecuta una vez y setup se repite", porque:"Es justo al revés."},
      {texto:"Son lo mismo con distinto nombre", porque:"No: si pones el programa en setup, solo se ejecutará al encender."}],
    porque:"setup prepara la placa al encender. loop es el programa en sí, que se repite mientras haya corriente." },

  { id:"rob-08", tema:"tec-robotica", etiqueta:"Arduino",
    enunciado:"Una LDR se conecta al pin A0. ¿Con qué se lee?",
    opciones:[{texto:"analogRead(A0)", bien:true},
      {texto:"digitalRead(A0)", porque:"digitalRead solo distingue HIGH o LOW. La luz varía poco a poco: necesita lectura analógica."},
      {texto:"digitalWrite(A0)", porque:"Write escribe, no lee."},
      {texto:"pinMode(A0)", porque:"pinMode configura, no lee valores."}],
    porque:"analogRead devuelve un número entre 0 y 1023 según la tensión: perfecto para luz, temperatura o un potenciómetro." },

  { id:"rob-09", tema:"tec-robotica", etiqueta:"Arduino",
    enunciado:"¿Por qué analogRead devuelve valores de 0 a 1023?",
    opciones:[{texto:"Porque el conversor es de 10 bits: 2¹⁰ = 1024 valores", bien:true},
      {texto:"Porque son 1023 milivoltios", porque:"El rango va de 0 a 5 V, dividido en 1024 escalones."},
      {texto:"Es un número elegido al azar", porque:"Viene de la resolución del conversor analógico-digital."},
      {texto:"Porque hay 1023 pines", porque:"Arduino Uno tiene 6 analógicos y 14 digitales."}],
    porque:"10 bits dan 1024 combinaciones: de 0 (0 V) a 1023 (5 V). Cada escalón son unos 4,9 mV." },

  { id:"rob-10", tema:"tec-robotica", etiqueta:"Robots",
    enunciado:"¿Qué hace falta para que una máquina sea un robot?",
    opciones:[{texto:"Que perciba su entorno y actúe según un programa", bien:true},
      {texto:"Que tenga forma humana", porque:"La mayoría de robots no la tienen: brazos industriales, aspiradores, drones."},
      {texto:"Que se mueva", porque:"Una batidora se mueve y no es un robot."},
      {texto:"Que hable", porque:"Hablar no es un requisito."}],
    porque:"Robot = sensores + controlador programable + actuadores. Percibe, decide y actúa." },

  { id:"rob-11", tema:"tec-robotica", etiqueta:"Actuadores",
    enunciado:"Para girar una barrera exactamente 90°, ¿qué actuador usarías?",
    opciones:[{texto:"Un servomotor", bien:true},
      {texto:"Un motor de corriente continua", porque:"Gira sin parar mientras le llega corriente: no sabe dónde está."},
      {texto:"Un LED", porque:"Es un actuador de luz, no de movimiento."},
      {texto:"Un pulsador", porque:"Es un sensor, no un actuador."}],
    porque:"El servo se controla por ángulo: le dices 90° y va a 90°. Por eso está en barreras, timones y brazos robóticos." },

  { id:"rob-12", tema:"tec-robotica", etiqueta:"Programa",
    enunciado:"En un robot seguidor de línea, si el sensor izquierdo ve la línea negra, el robot debe…",
    opciones:[{texto:"Girar a la izquierda para volver a centrarse", bien:true},
      {texto:"Girar a la derecha", porque:"Se alejaría todavía más de la línea."},
      {texto:"Pararse", porque:"Se pararía cada vez que se desviara un poco."},
      {texto:"Ir recto más rápido", porque:"Seguiría saliéndose."}],
    porque:"Es un lazo cerrado: el sensor detecta el desvío y el programa corrige hacia el lado de la línea." }
);
