/* preguntas-fyq.js — banco de Física y Química. Se suma al banco común. */
BANCO.push(
  { id:"atom-01", tema:"fyq-atomo", etiqueta:"Partículas",
    enunciado:"¿Qué partícula determina de qué elemento se trata?",
    opciones:[{texto:"El protón", bien:true},
      {texto:"El neutrón", porque:"Si cambian los neutrones sigue siendo el mismo elemento: es un isótopo suyo."},
      {texto:"El electrón", porque:"Si cambian los electrones sigue siendo el mismo elemento, pero con carga: un ion."},
      {texto:"Todas por igual", porque:"No: el carné de identidad del elemento es el número de protones."}],
    porque:"El número de protones es el número atómico Z, y es lo que define el elemento. 6 protones son carbono, siempre." },

  { id:"atom-02", tema:"fyq-atomo", etiqueta:"Partículas",
    enunciado:"En $^{23}_{11}\\text{Na}$, ¿cuántos neutrones hay?",
    opciones:[{texto:"12", bien:true},
      {texto:"11", porque:"Ese es Z, el número de protones."},
      {texto:"23", porque:"Ese es A: protones y neutrones juntos."},
      {texto:"34", porque:"Has sumado A + Z en vez de restar."}],
    porque:"Neutrones = A − Z = 23 − 11 = 12." },

  { id:"atom-03", tema:"fyq-atomo", etiqueta:"Iones",
    enunciado:"El ion $\\text{Ca}^{2+}$ (Z = 20) tiene…",
    opciones:[{texto:"20 protones y 18 electrones", bien:true},
      {texto:"20 protones y 22 electrones", porque:"El signo + significa que ha perdido electrones, no que los haya ganado."},
      {texto:"18 protones y 18 electrones", porque:"Los protones no cambian nunca: si cambiaran, ya no sería calcio."},
      {texto:"22 protones y 20 electrones", porque:"Has cambiado los protones, que son fijos."}],
    porque:"Carga +2 significa que ha perdido 2 electrones: 20 protones y 20 − 2 = 18 electrones." },

  { id:"atom-04", tema:"fyq-atomo", etiqueta:"Isótopos",
    enunciado:"Dos isótopos del mismo elemento se diferencian en…",
    opciones:[{texto:"El número de neutrones", bien:true},
      {texto:"El número de protones", porque:"Entonces serían elementos distintos, no isótopos."},
      {texto:"El número de electrones", porque:"Eso sería un ion, no un isótopo."},
      {texto:"Sus propiedades químicas", porque:"Justo al revés: se comportan químicamente igual, porque tienen los mismos electrones."}],
    porque:"Mismo Z, distinta A. Cambian los neutrones, así que pesan distinto pero reaccionan igual." },

  { id:"atom-05", tema:"fyq-atomo", etiqueta:"Modelos",
    enunciado:"El experimento de Rutherford con la lámina de oro demostró que…",
    opciones:[{texto:"El átomo está casi vacío, con la masa concentrada en el núcleo", bien:true},
      {texto:"Los electrones están en órbitas de energía fija", porque:"Eso lo propuso Bohr después, para explicar los espectros."},
      {texto:"El átomo es una masa positiva con electrones incrustados", porque:"Ese era el modelo de Thomson, y el experimento sirvió justo para tumbarlo."},
      {texto:"Los átomos son indivisibles", porque:"Eso era Dalton, un siglo antes."}],
    porque:"Casi todas las partículas atravesaban la lámina sin desviarse, y unas pocas rebotaban: hay mucho vacío y un núcleo pequeño y denso." },

  { id:"atom-06", tema:"fyq-atomo", etiqueta:"Configuración",
    enunciado:"La configuración electrónica del oxígeno (Z = 8) es…",
    opciones:[{texto:"$1s^2\\ 2s^2\\ 2p^4$", bien:true},
      {texto:"$1s^2\\ 2s^2\\ 2p^6$", porque:"Esos son 10 electrones: el neón. El oxígeno tiene 8."},
      {texto:"$1s^2\\ 2s^6$", porque:"En un orbital s solo caben 2 electrones, nunca 6."},
      {texto:"$1s^8$", porque:"En la primera capa solo caben 2."}],
    porque:"8 electrones: 2 en 1s, 2 en 2s y los 4 que quedan en 2p." },

  { id:"atom-07", tema:"fyq-atomo", etiqueta:"Configuración",
    enunciado:"¿Cuántos electrones caben como máximo en un conjunto de orbitales p?",
    opciones:[{texto:"6", bien:true},
      {texto:"2", porque:"Eso es lo que cabe en un orbital s."},
      {texto:"8", porque:"8 es la regla del octeto (la capa completa), no lo que cabe en p."},
      {texto:"10", porque:"10 es lo que cabe en los orbitales d."}],
    porque:"Hay tres orbitales p y en cada uno caben 2 electrones: 3 × 2 = 6." },

  { id:"atom-08", tema:"fyq-atomo", etiqueta:"Tabla periódica",
    enunciado:"Los elementos de un mismo grupo (columna) tienen en común…",
    opciones:[{texto:"El número de electrones en la última capa", bien:true},
      {texto:"El número de capas", porque:"Eso es lo que comparten los de un mismo periodo (fila)."},
      {texto:"La masa atómica", porque:"La masa crece al bajar por el grupo."},
      {texto:"El número de protones", porque:"Ese es distinto en cada elemento: es lo que los diferencia."}],
    porque:"Misma columna significa mismos electrones de valencia, y por eso se comportan de forma parecida." },

  { id:"atom-09", tema:"fyq-atomo", etiqueta:"Tabla periódica",
    enunciado:"¿Por qué los gases nobles casi no reaccionan?",
    opciones:[{texto:"Porque tienen la última capa completa", bien:true},
      {texto:"Porque son muy pesados", porque:"El helio es de los más ligeros que hay, y tampoco reacciona."},
      {texto:"Porque no tienen electrones", porque:"Sí los tienen; lo que pasa es que los tienen bien colocados."},
      {texto:"Porque son gases", porque:"El oxígeno también es gas y reacciona con casi todo."}],
    porque:"Con 8 electrones en la última capa (2 en el helio) ya están estables: no ganan nada uniéndose a nadie." },

  { id:"atom-10", tema:"fyq-atomo", etiqueta:"Tabla periódica",
    enunciado:"El sodio (Z = 11) tiende a…",
    opciones:[{texto:"Perder 1 electrón y quedar como $\\text{Na}^{+}$", bien:true},
      {texto:"Ganar 7 electrones", porque:"Le costaría muchísimo: es mucho más fácil soltar uno que capturar siete."},
      {texto:"Ganar 1 electrón", porque:"Ganarlo lo dejaría peor, no mejor: quedaría con 2 en la última capa."},
      {texto:"No hacer nada", porque:"El sodio es de los elementos más reactivos que existen."}],
    porque:"Tiene 1 electrón en la última capa. Soltándolo se queda con la capa anterior completa, como el neón." },

  { id:"atom-11", tema:"fyq-atomo", etiqueta:"Propiedades periódicas",
    enunciado:"Al bajar por un grupo, el tamaño del átomo…",
    opciones:[{texto:"Aumenta, porque se añaden capas", bien:true},
      {texto:"Disminuye", porque:"Al revés: cada periodo añade una capa entera de electrones."},
      {texto:"No cambia", porque:"Cambia mucho: el potasio es bastante más grande que el litio."},
      {texto:"Depende del número de neutrones", porque:"Los neutrones están en el núcleo, que es minúsculo frente al átomo entero."}],
    porque:"Bajar un periodo es añadir una capa, y el átomo se hace más grande." },

  { id:"atom-12", tema:"fyq-atomo", etiqueta:"Masa atómica",
    enunciado:"¿Por qué la masa atómica del cloro es 35,45 y no un número entero?",
    opciones:[{texto:"Porque es la media de sus isótopos", bien:true},
      {texto:"Porque los electrones pesan y se suman", porque:"El electrón pesa unas 1.800 veces menos que un protón: es despreciable."},
      {texto:"Porque está mal medida", porque:"Está medidísima: es una media real."},
      {texto:"Porque incluye los neutrones", porque:"Los neutrones ya están contados en el número másico, que sí es entero."}],
    porque:"En la naturaleza hay cloro-35 y cloro-37 mezclados. La masa de la tabla es la media ponderada de los dos." },

  { id:"atom-13", tema:"fyq-atomo", etiqueta:"Escala",
    enunciado:"Si el núcleo de un átomo fuera una canica en el centro de un campo de fútbol, los electrones estarían…",
    opciones:[{texto:"Por las gradas: el átomo está casi vacío", bien:true},
      {texto:"Pegados a la canica", porque:"Entonces el átomo sería casi todo núcleo, y no lo es."},
      {texto:"A un metro de la canica", porque:"Te quedas muy corto: la diferencia es de unas 100.000 veces."},
      {texto:"Dentro de la canica", porque:"Dentro del núcleo están los protones y neutrones, no los electrones."}],
    porque:"El núcleo es unas 100.000 veces más pequeño que el átomo. Casi todo lo que tocas es espacio vacío." },

  { id:"atom-14", tema:"fyq-atomo", etiqueta:"Problema",
    enunciado:"Un átomo tiene 17 protones, 18 neutrones y 17 electrones. ¿Qué es?",
    opciones:[{texto:"Un átomo neutro de cloro, $^{35}\\text{Cl}$", bien:true},
      {texto:"Un ion cloruro $\\text{Cl}^{-}$", porque:"Sería un ion si tuviera 18 electrones; aquí hay los mismos que protones."},
      {texto:"Un átomo de argón", porque:"El argón tiene 18 protones. Aquí hay 17: es cloro."},
      {texto:"Un isótopo del azufre", porque:"El azufre tiene 16 protones."}],
    porque:"17 protones es cloro. A = 17 + 18 = 35, y al tener los mismos electrones que protones, es neutro." }
);
