/* preguntas-guerras.js — banco de las guerras mundiales. */
BANCO.push(
  { id:"gue-01", tema:"his-guerras", etiqueta:"IGM causas",
    enunciado:"¿Qué hecho desencadenó la Primera Guerra Mundial en 1914?",
    opciones:[{texto:"El asesinato del archiduque Francisco Fernando en Sarajevo", bien:true},
      {texto:"La invasión de Polonia", porque:"Eso desencadenó la Segunda, en 1939."},
      {texto:"La Revolución Rusa", porque:"Fue en 1917, con la guerra ya empezada."},
      {texto:"El crac del 29", porque:"Fue once años después de que acabara."}],
    porque:"Fue la chispa, no la causa de fondo. Las causas profundas eran la rivalidad imperialista, el nacionalismo, la carrera de armamentos y las alianzas." },

  { id:"gue-02", tema:"his-guerras", etiqueta:"IGM causas",
    enunciado:"¿Por qué un asesinato en Sarajevo acabó en guerra mundial?",
    opciones:[{texto:"Por el sistema de alianzas, que arrastró a unos países tras otros", bien:true},
      {texto:"Porque el archiduque era el rey de Francia", porque:"Era el heredero del Imperio austrohúngaro."},
      {texto:"Porque Estados Unidos declaró la guerra enseguida", porque:"EE. UU. no entró hasta 1917."},
      {texto:"Porque Serbia invadió Alemania", porque:"Fue Austria-Hungría quien atacó a Serbia."}],
    porque:"Austria atacó a Serbia; Rusia apoyó a Serbia; Alemania, a Austria; Francia y Reino Unido, a Rusia. En un mes, media Europa estaba en guerra." },

  { id:"gue-03", tema:"his-guerras", etiqueta:"IGM",
    enunciado:"¿Cómo era la guerra en el frente occidental?",
    opciones:[{texto:"Una guerra de trincheras casi inmóvil durante años", bien:true},
      {texto:"Una guerra relámpago de tanques", porque:"Eso es la Blitzkrieg alemana de la Segunda Guerra Mundial."},
      {texto:"Se luchó sobre todo en el mar", porque:"Hubo guerra naval, pero lo decisivo fue en tierra."},
      {texto:"Terminó en pocos meses", porque:"Todos creían eso en 1914. Duró más de cuatro años."}],
    porque:"Desde finales de 1914 el frente apenas se movió: millones de muertos para ganar unos kilómetros." },

  { id:"gue-04", tema:"his-guerras", etiqueta:"Revolución Rusa",
    enunciado:"¿Qué consecuencia tuvo la Revolución Rusa de 1917 en la guerra?",
    opciones:[{texto:"Rusia se retiró de la guerra", bien:true},
      {texto:"Rusia entró en la guerra", porque:"Rusia estaba desde 1914. La revolución la sacó."},
      {texto:"Rusia se pasó al bando alemán", porque:"Firmó la paz con Alemania (Brest-Litovsk, 1918), pero no se unió a ella."},
      {texto:"Ninguna", porque:"Liberó a Alemania del frente oriental."}],
    porque:"Los bolcheviques firmaron la paz con Alemania en 1918. Nacía el primer estado comunista, la futura URSS." },

  { id:"gue-05", tema:"his-guerras", etiqueta:"Versalles",
    enunciado:"¿Qué impuso el Tratado de Versalles (1919) a Alemania?",
    opciones:[{texto:"Culpa de la guerra, pérdida de territorios y enormes reparaciones", bien:true},
      {texto:"Que se uniera a Austria", porque:"Precisamente lo prohibió."},
      {texto:"Que construyera un gran ejército", porque:"Limitó su ejército a 100.000 hombres."},
      {texto:"Nada, porque Alemania ganó", porque:"Alemania perdió la guerra."}],
    porque:"Los alemanes lo vivieron como una humillación. Hitler lo explotó después: por eso se dice que Versalles sembró la Segunda Guerra." },

  { id:"gue-06", tema:"his-guerras", etiqueta:"Crisis del 29",
    enunciado:"¿Qué relación hay entre el crac de 1929 y el ascenso del nazismo?",
    opciones:[{texto:"La crisis disparó el paro y la desesperación, y el nazismo creció con ella", bien:true},
      {texto:"Ninguna: pasaron en continentes distintos", porque:"La crisis empezó en EE. UU. pero se extendió a Europa, y a Alemania con fuerza."},
      {texto:"El nazismo provocó el crac", porque:"El crac empezó en la Bolsa de Nueva York."},
      {texto:"La crisis acabó con el nazismo", porque:"Fue al revés: lo impulsó."}],
    porque:"En 1932 había unos seis millones de parados en Alemania. Ese año los nazis fueron el partido más votado; en 1933 Hitler llegó a canciller." },

  { id:"gue-07", tema:"his-guerras", etiqueta:"Totalitarismos",
    enunciado:"¿Qué tenían en común el fascismo italiano y el nazismo alemán?",
    opciones:[{texto:"Partido único, culto al líder y eliminación de la oposición", bien:true},
      {texto:"Eran democracias parlamentarias", porque:"Acabaron con la democracia."},
      {texto:"Defendían el comunismo", porque:"Eran profundamente anticomunistas."},
      {texto:"Rechazaban el nacionalismo", porque:"El nacionalismo extremo era su base."}],
    porque:"El nazismo añadía el racismo como eje central: la idea de una «raza superior» que llevó al Holocausto." },

  { id:"gue-08", tema:"his-guerras", etiqueta:"IIGM",
    enunciado:"¿Qué hecho inició la Segunda Guerra Mundial?",
    opciones:[{texto:"La invasión alemana de Polonia en 1939", bien:true},
      {texto:"El ataque a Pearl Harbor", porque:"Fue en 1941 y metió a EE. UU. en la guerra, que ya llevaba dos años."},
      {texto:"El desembarco de Normandía", porque:"Fue en 1944, cerca del final."},
      {texto:"La anexión de Austria", porque:"Fue en 1938: Francia y Reino Unido todavía intentaban evitar la guerra."}],
    porque:"Francia y Reino Unido habían garantizado la defensa de Polonia y declararon la guerra a Alemania." },

  { id:"gue-09", tema:"his-guerras", etiqueta:"IIGM bandos",
    enunciado:"¿Qué países formaban el Eje?",
    opciones:[{texto:"Alemania, Italia y Japón", bien:true},
      {texto:"Alemania, Austria-Hungría y el Imperio otomano", porque:"Esos son los Imperios Centrales de la Primera Guerra."},
      {texto:"Alemania, URSS y Japón", porque:"La URSS luchó con los Aliados desde 1941."},
      {texto:"Alemania, España e Italia", porque:"España no entró en la guerra, aunque envió la División Azul contra la URSS."}],
    porque:"Eje: Alemania, Italia y Japón. Aliados: Reino Unido, URSS, EE. UU., China, Francia libre…" },

  { id:"gue-10", tema:"his-guerras", etiqueta:"IIGM",
    enunciado:"¿Por qué se considera Stalingrado (1942-43) un punto de inflexión?",
    opciones:[{texto:"Fue la primera gran derrota alemana y la URSS empezó a avanzar", bien:true},
      {texto:"Porque terminó la guerra", porque:"La guerra siguió dos años más."},
      {texto:"Porque Japón se rindió allí", porque:"Stalingrado está en Rusia; Japón no participó."},
      {texto:"Porque fue la primera batalla con armas atómicas", porque:"Las bombas atómicas fueron en Japón en 1945."}],
    porque:"Desde Stalingrado, Alemania ya no volvió a avanzar en el este." },

  { id:"gue-11", tema:"his-guerras", etiqueta:"Holocausto",
    enunciado:"¿Qué fue el Holocausto?",
    opciones:[{texto:"El exterminio planificado de unos seis millones de judíos por el régimen nazi", bien:true},
      {texto:"Una batalla de la Segunda Guerra Mundial", porque:"No fue una batalla: fue un genocidio organizado contra civiles."},
      {texto:"Los bombardeos sobre Alemania", porque:"Esos fueron ataques aliados; el Holocausto fue obra de los nazis."},
      {texto:"Una consecuencia accidental de la guerra", porque:"Fue deliberado: se planificó en la conferencia de Wannsee, en 1942."}],
    porque:"Además de los judíos, los nazis asesinaron a gitanos, discapacitados, homosexuales y opositores. Auschwitz fue liberado el 27 de enero de 1945." },

  { id:"gue-12", tema:"his-guerras", etiqueta:"Consecuencias",
    enunciado:"¿Cuál fue una consecuencia de la Segunda Guerra Mundial?",
    opciones:[{texto:"El mundo quedó dividido entre EE. UU. y la URSS: la Guerra Fría", bien:true},
      {texto:"Alemania se convirtió en la mayor potencia", porque:"Quedó destruida y dividida en dos."},
      {texto:"Desapareció el Imperio austrohúngaro", porque:"Eso fue tras la Primera Guerra."},
      {texto:"Se creó la Sociedad de Naciones", porque:"Esa fue en 1919. Tras la Segunda se creó la ONU."}],
    porque:"Murieron más de 60 millones de personas. Se creó la ONU (1945), Alemania se dividió y empezó la Guerra Fría." }
);
