/* preguntas-ingles.js — banco de inglés. */
BANCO.push(
  { id:"ing-01", tema:"ing-tenses", etiqueta:"Present perfect",
    enunciado:"«I ____ to London twice.» ¿Qué falta?",
    opciones:[{texto:"have been", bien:true},
      {texto:"went", porque:"«Twice» no dice cuándo: es experiencia acumulada, así que present perfect."},
      {texto:"have gone", porque:"«Have gone» significa que sigue allí. Para experiencias se usa «have been»."},
      {texto:"am going", porque:"Eso sería un plan o algo en marcha, no algo que ya pasó dos veces."}],
    porque:"Experiencia sin fecha concreta: present perfect. Y «been» para «he estado (y he vuelto)»." },

  { id:"ing-02", tema:"ing-tenses", etiqueta:"Past simple",
    enunciado:"¿Cuál es correcta?",
    opciones:[{texto:"I didn't see him yesterday", bien:true},
      {texto:"I didn't saw him yesterday", porque:"Tras «did/didn't» va siempre el infinitivo: el pasado ya lo marca el auxiliar."},
      {texto:"I don't saw him yesterday", porque:"Dos errores: el auxiliar debe ir en pasado y el verbo en infinitivo."},
      {texto:"I haven't seen him yesterday", porque:"«Yesterday» es momento cerrado: no admite present perfect."}],
    porque:"Negativa en pasado: didn't + infinitivo. Es de los errores que más se repiten." },

  { id:"ing-03", tema:"ing-tenses", etiqueta:"Past simple vs perfect",
    enunciado:"«I ____ my keys. I can't open the door.» ¿Qué encaja mejor?",
    opciones:[{texto:"have lost", bien:true},
      {texto:"lost", porque:"Se puede decir, pero el present perfect explica mejor la consecuencia de ahora: por eso no puedo abrir."},
      {texto:"am losing", porque:"Perder no es una acción en progreso."},
      {texto:"had lost", porque:"El past perfect necesita otro momento pasado como referencia, y aquí no lo hay."}],
    porque:"Present perfect: acción pasada con efecto en el presente. Ese es su uso principal." },

  { id:"ing-04", tema:"ing-tenses", etiqueta:"Marcadores",
    enunciado:"¿Cuál de estas palabras NO va con present perfect?",
    opciones:[{texto:"two years ago", bien:true},
      {texto:"since", porque:"«Since» es de los suyos: desde un punto del pasado hasta ahora."},
      {texto:"yet", porque:"«Yet» va con present perfect en negativas y preguntas."},
      {texto:"just", porque:"«Just» significa «acabo de»: present perfect puro."}],
    porque:"«Ago» siempre pide past simple, porque cierra el momento: hace dos años." },

  { id:"ing-05", tema:"ing-tenses", etiqueta:"For / Since",
    enunciado:"«I have lived here ____ 2018.»",
    opciones:[{texto:"since", bien:true},
      {texto:"for", porque:"«For» va con duración: for five years. 2018 es un punto de partida."},
      {texto:"during", porque:"«During» va con un periodo entero: during the summer."},
      {texto:"from", porque:"«From» necesita su «to»: from 2018 to 2020."}],
    porque:"«Since» + momento de inicio; «for» + cuánto tiempo. Es la pareja que más se confunde." },

  { id:"ing-06", tema:"ing-tenses", etiqueta:"Past continuous",
    enunciado:"«While I ____ dinner, the phone rang.»",
    opciones:[{texto:"was cooking", bien:true},
      {texto:"cooked", porque:"«While» pide la acción larga en past continuous: era el fondo de lo que pasó."},
      {texto:"have cooked", porque:"El present perfect no se mezcla con un past simple así."},
      {texto:"am cooking", porque:"El presente no encaja: todo el relato está en pasado."}],
    porque:"Acción larga de fondo (past continuous) interrumpida por una corta (past simple). Es el patrón clásico." },

  { id:"ing-07", tema:"ing-tenses", etiqueta:"Present simple",
    enunciado:"¿Cuál es correcta?",
    opciones:[{texto:"She doesn't like coffee", bien:true},
      {texto:"She don't like coffee", porque:"Tercera persona del singular: doesn't."},
      {texto:"She doesn't likes coffee", porque:"La «s» ya está en «does»: el verbo va en infinitivo."},
      {texto:"She not like coffee", porque:"Falta el auxiliar: en inglés la negación necesita do/does."}],
    porque:"He, she, it → does / doesn't, y detrás el verbo sin «s»." },

  { id:"ing-08", tema:"ing-tenses", etiqueta:"Futuro",
    enunciado:"«Look at those clouds! It ____ rain.»",
    opciones:[{texto:"is going to", bien:true},
      {texto:"will", porque:"«Will» es para decisiones del momento o predicciones sin pruebas. Aquí hay pruebas: las nubes."},
      {texto:"is raining", porque:"Todavía no llueve: se ve venir."},
      {texto:"rains", porque:"El presente simple es para rutinas, no para lo que va a pasar."}],
    porque:"«Going to» cuando hay una señal visible de que va a ocurrir. «Will» cuando lo decides o lo crees sin pruebas." },

  { id:"ing-09", tema:"ing-tenses", etiqueta:"Futuro",
    enunciado:"«I ____ dinner with Ana tomorrow at eight.» (ya está acordado)",
    opciones:[{texto:"am having", bien:true},
      {texto:"will have", porque:"«Will» no se usa para planes ya cerrados con otra persona."},
      {texto:"have", porque:"El presente simple, para el futuro, solo vale con horarios fijos (trenes, clases)."},
      {texto:"had", porque:"Eso es pasado, y la frase dice «tomorrow»."}],
    porque:"Planes acordados con hora y persona: present continuous con valor de futuro." },

  { id:"ing-10", tema:"ing-tenses", etiqueta:"Past perfect",
    enunciado:"«When I arrived, the film ____ already ____.»",
    opciones:[{texto:"had / started", bien:true},
      {texto:"has / started", porque:"El present perfect no se usa cuando todo el relato es pasado."},
      {texto:"was / starting", porque:"Eso sería que estaba empezando justo entonces, y «already» dice que fue antes."},
      {texto:"did / start", porque:"No hay auxiliar «did» en afirmativas."}],
    porque:"Past perfect: lo que pasó ANTES de otro momento pasado. La película empezó antes de que yo llegara." },

  { id:"ing-11", tema:"ing-tenses", etiqueta:"Error de españoles",
    enunciado:"¿Cómo se dice «Llevo dos años estudiando inglés»?",
    opciones:[{texto:"I have been studying English for two years", bien:true},
      {texto:"I study English since two years", porque:"Dos errores típicos del español: hace falta present perfect, y con duración va «for», no «since»."},
      {texto:"I am studying English since two years", porque:"El presente continuo no sirve para algo que viene del pasado."},
      {texto:"I studied English for two years", porque:"Eso significa que ya no estudias: está terminado."}],
    porque:"«Llevo + tiempo + haciendo algo» se traduce con present perfect continuous + for. Es de los que más delatan a un hispanohablante." },

  { id:"ing-12", tema:"ing-tenses", etiqueta:"Preguntas",
    enunciado:"¿Cuál es la pregunta correcta?",
    opciones:[{texto:"Where did you go last night?", bien:true},
      {texto:"Where did you went last night?", porque:"Tras «did», infinitivo."},
      {texto:"Where you went last night?", porque:"Falta el auxiliar: en inglés las preguntas lo necesitan."},
      {texto:"Where have you gone last night?", porque:"«Last night» cierra el momento: no admite present perfect."}],
    porque:"Pregunta en pasado: did + sujeto + infinitivo." },

  { id:"ing-13", tema:"ing-tenses", etiqueta:"Verbos de estado",
    enunciado:"¿Cuál de estas NO se dice normalmente en continuo?",
    opciones:[{texto:"I am knowing the answer", bien:true},
      {texto:"I am reading a book", porque:"Leer es una acción: admite continuo perfectamente."},
      {texto:"I am waiting for you", porque:"Esperar también es acción en curso."},
      {texto:"I am learning English", porque:"Aprender es un proceso: continuo correcto."}],
    porque:"Los verbos de estado (know, like, want, need, believe) no van en continuo: se dice «I know»." },

  { id:"ing-14", tema:"ing-tenses", etiqueta:"Elegir",
    enunciado:"«She ____ in Madrid for five years, but now she lives in Paris.»",
    opciones:[{texto:"lived", bien:true},
      {texto:"has lived", porque:"El present perfect diría que sigue viviendo allí, y la frase dice que ya no."},
      {texto:"is living", porque:"Eso sería ahora mismo, y ahora está en París."},
      {texto:"has been living", porque:"También implicaría que continúa."}],
    porque:"Terminado y cerrado: past simple. El «for five years» no obliga al present perfect si la etapa ya acabó." }
);
