/* preguntas-morfo.js — categorías gramaticales. */
BANCO.push(
  { id:"morfo-01", tema:"len-morfologia", etiqueta:"Determinante o pronombre",
    enunciado:"En «Este es mi coche», la palabra «Este» es…",
    opciones:[{texto:"Pronombre", bien:true},
      {texto:"Determinante", porque:"Sería determinante si acompañara a un sustantivo: «Este coche». Aquí va solo."},
      {texto:"Adjetivo", porque:"Los demostrativos no son adjetivos: o acompañan (determinante) o sustituyen (pronombre)."},
      {texto:"Adverbio", porque:"No dice cómo, cuándo ni dónde."}],
    porque:"Va solo, sin sustantivo detrás: ha sustituido al nombre. La regla: si acompaña, determinante; si va solo, pronombre." },

  { id:"morfo-02", tema:"len-morfologia", etiqueta:"Adjetivo o adverbio",
    enunciado:"En «Habla muy bajo», ¿qué es «bajo»?",
    opciones:[{texto:"Adverbio", bien:true},
      {texto:"Adjetivo", porque:"No acompaña a ningún sustantivo ni concuerda con nada: dice cómo habla."},
      {texto:"Sustantivo", porque:"No nombra ninguna cosa."},
      {texto:"Preposición", porque:"Sería preposición en «bajo la mesa», donde relaciona dos palabras."},],
    porque:"Modifica al verbo «habla» y es invariable: adverbio de modo. «Bajo» puede ser adjetivo, adverbio o preposición según la frase." },

  { id:"morfo-03", tema:"len-morfologia", etiqueta:"Invariabilidad",
    enunciado:"¿Cómo se distingue rápido de rápidamente?",
    opciones:[{texto:"«Rápido» concuerda en género y número; «rápidamente» nunca cambia", bien:true},
      {texto:"Son lo mismo", porque:"Uno es adjetivo y el otro adverbio: hacen cosas distintas."},
      {texto:"«Rápidamente» es más culto", porque:"No es cuestión de registro sino de categoría."},
      {texto:"«Rápido» solo va con personas", porque:"Un coche rápido también vale."}],
    porque:"Los adjetivos cambian (rápida, rápidos); los adverbios son invariables. Esa es la prueba." },

  { id:"morfo-04", tema:"len-morfologia", etiqueta:"Preposición",
    enunciado:"¿Cuál de estas NO es una preposición?",
    opciones:[{texto:"cuando", bien:true},
      {texto:"hacia", porque:"Sí lo es: está en la lista."},
      {texto:"mediante", porque:"También es preposición."},
      {texto:"según", porque:"Es preposición, aunque poco frecuente."}],
    porque:"«Cuando» une oraciones: es conjunción o adverbio relativo, no preposición." },

  { id:"morfo-05", tema:"len-morfologia", etiqueta:"Conjunción",
    enunciado:"En «Estudia, pero no aprueba», la palabra «pero» es…",
    opciones:[{texto:"Conjunción adversativa", bien:true},
      {texto:"Preposición", porque:"Las preposiciones relacionan palabras dentro de una oración, no unen dos oraciones."},
      {texto:"Adverbio", porque:"No dice cómo, cuándo ni dónde."},
      {texto:"Interjección", porque:"No expresa una emoción."}],
    porque:"Une dos oraciones oponiendo lo que dicen: adversativa. Como «sin embargo» o «aunque»." },

  { id:"morfo-06", tema:"len-morfologia", etiqueta:"Verbo",
    enunciado:"¿Qué es una perífrasis verbal?",
    opciones:[{texto:"Dos o más verbos que funcionan como uno solo", bien:true},
      {texto:"Un verbo muy largo", porque:"No tiene que ver con la longitud."},
      {texto:"Un verbo irregular", porque:"Eso es otra cosa: los irregulares cambian su raíz."},
      {texto:"Un verbo con complemento", porque:"Cualquier verbo puede llevar complementos."}],
    porque:"«Tengo que estudiar», «está lloviendo», «voy a salir»: un auxiliar más un verbo en forma no personal, y juntos son un solo núcleo." },

  { id:"morfo-07", tema:"len-morfologia", etiqueta:"Formación",
    enunciado:"«Sacacorchos» se ha formado por…",
    opciones:[{texto:"Composición", bien:true},
      {texto:"Derivación", porque:"En la derivación se añaden prefijos o sufijos; aquí se juntan dos palabras completas."},
      {texto:"Acortamiento", porque:"Nada se ha cortado: se ha alargado."},
      {texto:"Préstamo", porque:"Es una palabra española, no viene de otro idioma."}],
    porque:"Se unen dos palabras que ya existían: «saca» y «corchos». Eso es composición." },

  { id:"morfo-08", tema:"len-morfologia", etiqueta:"Formación",
    enunciado:"En «panadero», la parte «-ero» es…",
    opciones:[{texto:"Un sufijo", bien:true},
      {texto:"Un prefijo", porque:"Los prefijos van delante: des-, in-, re-."},
      {texto:"La raíz", porque:"La raíz es «pan», la parte que lleva el significado."},
      {texto:"Una desinencia", porque:"Las desinencias marcan género, número, persona o tiempo, no crean palabras nuevas."}],
    porque:"Va detrás de la raíz y crea una palabra nueva: sufijo. Raíz «pan» + sufijo «-ero»." },

  { id:"morfo-09", tema:"len-morfologia", etiqueta:"Pronombre",
    enunciado:"En «Se lo dije ayer», «lo» es…",
    opciones:[{texto:"Pronombre personal (complemento directo)", bien:true},
      {texto:"Artículo", porque:"El artículo neutro «lo» va delante de un adjetivo: «lo bueno». Aquí no acompaña a nada."},
      {texto:"Determinante", porque:"No hay sustantivo al que acompañar."},
      {texto:"Conjunción", porque:"No une nada."}],
    porque:"Sustituye a lo que se dijo: es pronombre personal átono, y hace de complemento directo." },

  { id:"morfo-10", tema:"len-morfologia", etiqueta:"Adverbio",
    enunciado:"¿Cuál de estas palabras es un adverbio?",
    opciones:[{texto:"Quizá", bien:true},
      {texto:"Bonito", porque:"Es adjetivo: concuerda con el sustantivo."},
      {texto:"Amistad", porque:"Es sustantivo: nombra algo."},
      {texto:"Aunque", porque:"Es conjunción: une oraciones."}],
    porque:"«Quizá» es adverbio de duda. Los adverbios son invariables y modifican verbos, adjetivos u otros adverbios." },

  { id:"morfo-11", tema:"len-morfologia", etiqueta:"Sustantivo",
    enunciado:"¿Cómo se reconoce un sustantivo con seguridad?",
    opciones:[{texto:"Se le puede poner un determinante delante", bien:true},
      {texto:"Nombra algo que se puede tocar", porque:"«Amistad» o «miedo» son sustantivos y no se tocan."},
      {texto:"Acaba en vocal", porque:"«Amor» o «papel» también son sustantivos."},
      {texto:"Va siempre al principio de la oración", porque:"Puede ir en cualquier posición."}],
    porque:"La prueba del determinante: si «el/la/un/una» encaja delante, es sustantivo. Funciona hasta con palabras raras." },

  { id:"morfo-12", tema:"len-morfologia", etiqueta:"Contexto",
    enunciado:"¿Puede una misma palabra ser de categorías distintas?",
    opciones:[{texto:"Sí: depende de su función en cada frase", bien:true},
      {texto:"No: cada palabra tiene una sola categoría", porque:"«Bajo» es adjetivo, adverbio o preposición según la frase."},
      {texto:"Solo los verbos", porque:"Pasa con muchas categorías."},
      {texto:"Solo en poesía", porque:"Pasa en el lenguaje de todos los días."}],
    porque:"La categoría se decide por lo que hace la palabra en esa frase, no por la palabra suelta. Por eso hay que analizar siempre en contexto." },

  { id:"morfo-13", tema:"len-morfologia", etiqueta:"Interjección",
    enunciado:"Las interjecciones…",
    opciones:[{texto:"Expresan emociones y funcionan solas", bien:true},
      {texto:"Unen dos oraciones", porque:"Eso lo hacen las conjunciones."},
      {texto:"Acompañan al sustantivo", porque:"Eso lo hacen los determinantes."},
      {texto:"No existen en español", porque:"Claro que existen: ay, uf, ojalá, hala."}],
    porque:"«¡Ay!», «¡Uf!», «¡Ojalá!»: no se relacionan con el resto de la oración, funcionan por su cuenta." },

  { id:"morfo-14", tema:"len-morfologia", etiqueta:"Problema",
    enunciado:"En «Mañana iré, pero llegaré tarde», ¿cuántos adverbios hay?",
    opciones:[{texto:"Dos: mañana y tarde", bien:true},
      {texto:"Uno: mañana", porque:"«Tarde» también dice cuándo, así que también es adverbio."},
      {texto:"Tres: mañana, pero y tarde", porque:"«Pero» es conjunción: une las dos oraciones."},
      {texto:"Ninguno", porque:"Hay dos palabras que dicen cuándo, y eso es un adverbio."}],
    porque:"«Mañana» y «tarde» dicen cuándo y son invariables: adverbios de tiempo. «Pero» une, así que es conjunción." }
);
