/* preguntas-cond.js — banco de conditionals and wish. */
BANCO.push(
  { id:"cond-01", tema:"ing-conditionals", etiqueta:"First",
    enunciado:"«If it ___ tomorrow, we'll stay at home.»",
    opciones:[{texto:"rains", bien:true},
      {texto:"will rain", porque:"Nunca «will» detrás de «if» en el first conditional. En español decimos «si llueve», no «si lloverá»: en inglés igual."},
      {texto:"would rain", porque:"«would» va en la otra mitad y en el second conditional."},
      {texto:"rained", porque:"Eso sería second conditional, y la otra mitad llevaría «would»."}],
    porque:"First conditional: if + present simple, will + infinitive." },

  { id:"cond-02", tema:"ing-conditionals", etiqueta:"Second",
    enunciado:"«If I ___ rich, I would buy a house.»",
    opciones:[{texto:"were", bien:true},
      {texto:"am", porque:"Con «would» en la otra mitad, la condición va en pasado: es imaginaria."},
      {texto:"would be", porque:"«would» nunca va en la parte del «if»."},
      {texto:"had been", porque:"Eso sería el third conditional, sobre el pasado."}],
    porque:"Second conditional: if + past simple. «were» con todas las personas es lo estándar («was» se oye, pero en exámenes, were)." },

  { id:"cond-03", tema:"ing-conditionals", etiqueta:"Third",
    enunciado:"«If she had studied, she ___ the exam.»",
    opciones:[{texto:"would have passed", bien:true},
      {texto:"would pass", porque:"Hablamos del pasado, que ya no se puede cambiar: hace falta «would have + participio»."},
      {texto:"will have passed", porque:"«will» no se usa en condicionales imaginarias."},
      {texto:"had passed", porque:"El past perfect va en la parte del «if», no en el resultado."}],
    porque:"Third conditional: if + past perfect, would have + past participle. Es arrepentimiento sobre algo que ya pasó." },

  { id:"cond-04", tema:"ing-conditionals", etiqueta:"Zero",
    enunciado:"«If you heat ice, it melts.» ¿Qué tipo es?",
    opciones:[{texto:"Zero conditional", bien:true},
      {texto:"First conditional", porque:"El first habla de una situación futura concreta y lleva «will». Esto es una verdad general."},
      {texto:"Second conditional", porque:"No hay nada imaginario: siempre pasa."},
      {texto:"Mixed", porque:"Los dos verbos están en presente."}],
    porque:"Zero: present + present, para hechos que siempre se cumplen." },

  { id:"cond-05", tema:"ing-conditionals", etiqueta:"Mixed",
    enunciado:"«If I had taken the job, I ___ in London now.»",
    opciones:[{texto:"would be living", bien:true},
      {texto:"would have lived", porque:"«now» pide un resultado en presente, no en pasado."},
      {texto:"will live", porque:"«will» no encaja en una situación imaginaria."},
      {texto:"had lived", porque:"El past perfect es para la condición, no para el resultado."}],
    porque:"Mixed: condición en el pasado (had taken) con resultado en el presente (would be … now)." },

  { id:"cond-06", tema:"ing-conditionals", etiqueta:"Unless",
    enunciado:"«You won't pass unless you study.» significa…",
    opciones:[{texto:"You won't pass if you don't study", bien:true},
      {texto:"You won't pass if you study", porque:"«unless» ya lleva la negación dentro: equivale a «if … not»."},
      {texto:"You will pass although you don't study", porque:"No hay idea de concesión."},
      {texto:"You will pass in case you study", porque:"«in case» es por si acaso, otra cosa."}],
    porque:"unless = if not. Por eso no se dice «unless you don't study»: sería una doble negación." },

  { id:"cond-07", tema:"ing-conditionals", etiqueta:"Wish",
    enunciado:"No sabes nadar y te fastidia. ¿Cómo se dice?",
    opciones:[{texto:"I wish I could swim.", bien:true},
      {texto:"I wish I can swim.", porque:"Detrás de «wish» sobre el presente se retrocede un tiempo: can → could."},
      {texto:"I wish I would swim.", porque:"«would» detrás de wish es para quejarse de lo que hace otro, no para habilidades."},
      {texto:"I wish I had swum.", porque:"Eso es arrepentirse de no haber nadado en un momento pasado."}],
    porque:"wish + past sobre el presente. Para habilidades, could." },

  { id:"cond-08", tema:"ing-conditionals", etiqueta:"Wish",
    enunciado:"Te arrepientes de no haber ido a la fiesta de ayer.",
    opciones:[{texto:"I wish I had gone to the party.", bien:true},
      {texto:"I wish I went to the party.", porque:"«went» sería un deseo sobre el presente. Para arrepentirse del pasado, past perfect."},
      {texto:"I wish I would go to the party.", porque:"«would» no se usa contigo mismo en wish."},
      {texto:"I wish I go to the party.", porque:"Detrás de wish nunca va el presente."}],
    porque:"Arrepentimiento sobre el pasado: wish + past perfect." },

  { id:"cond-09", tema:"ing-conditionals", etiqueta:"Wish",
    enunciado:"Tu hermano pone la música muy alta. Te quejas:",
    opciones:[{texto:"I wish you would turn it down.", bien:true},
      {texto:"I wish you turned it down.", porque:"Se entiende, pero para quejarse de lo que hace otra persona lo natural es «would»."},
      {texto:"I wish you had turned it down.", porque:"Eso sería sobre algo pasado, no sobre lo que está pasando."},
      {texto:"I wish you will turn it down.", porque:"«will» nunca va detrás de wish."}],
    porque:"wish + would: queja sobre el comportamiento de otro que querrías que cambiara." },

  { id:"cond-10", tema:"ing-conditionals", etiqueta:"Errores",
    enunciado:"¿Qué frase es correcta?",
    opciones:[{texto:"If I had known, I would have told you.", bien:true},
      {texto:"If I would have known, I would have told you.", porque:"«would» nunca en las dos mitades. Es el error más típico de hispanohablantes (en español: «si hubiera sabido»)."},
      {texto:"If I knew, I would have told you.", porque:"Mezcla un second con un third sin sentido."},
      {texto:"If I have known, I would tell you.", porque:"«have known» no encaja con ningún tipo."}],
    porque:"Tercer tipo: if + had + participio. El «would» va solo en el resultado." },

  { id:"cond-11", tema:"ing-conditionals", etiqueta:"In case",
    enunciado:"«Take an umbrella ___ it rains.»",
    opciones:[{texto:"in case", bien:true},
      {texto:"if", porque:"«if» significaría llevarlo solo cuando llueva. Aquí es llevarlo por si acaso."},
      {texto:"unless", porque:"«unless it rains» = si no llueve: el sentido sería absurdo."},
      {texto:"as long as", porque:"«as long as» pone una condición obligatoria, no una precaución."}],
    porque:"in case = por si acaso: haces algo antes, como precaución." },

  { id:"cond-12", tema:"ing-conditionals", etiqueta:"Second vs first",
    enunciado:"¿Qué diferencia hay entre «If I win, I'll…» y «If I won, I'd…»?",
    opciones:[{texto:"La primera es posible; la segunda, poco probable o imaginaria", bien:true},
      {texto:"La segunda habla del pasado", porque:"«won» parece pasado, pero en el second conditional habla del presente o futuro imaginario."},
      {texto:"Ninguna, significan lo mismo", porque:"Cambia cuánto crees que va a pasar."},
      {texto:"La primera es más formal", porque:"No es cuestión de registro."}],
    porque:"First: lo ves posible (una carrera que puedes ganar). Second: lo ves lejano (la lotería)." }
);
