/* preguntas-form.js — banco de formulación inorgánica. */
BANCO.push(
  { id:"form-01", tema:"fyq-formulacion-inorganica", etiqueta:"Números de oxidación",
    enunciado:"¿Con qué número de oxidación actúa el oxígeno casi siempre?",
    opciones:[{texto:"−2", bien:true},
      {texto:"+2", porque:"El oxígeno es de los que más atraen electrones: queda negativo, no positivo."},
      {texto:"−1", porque:"Solo en los peróxidos, que son la excepción rara."},
      {texto:"0", porque:"Cero solo cuando está solo, como O₂. Dentro de un compuesto, no."}],
    porque:"El oxígeno actúa con −2 salvo en los peróxidos. Es la regla en la que se apoya todo lo demás." },

  { id:"form-02", tema:"fyq-formulacion-inorganica", etiqueta:"Números de oxidación",
    enunciado:"En el NaH, el hidrógeno actúa con…",
    opciones:[{texto:"−1", bien:true},
      {texto:"+1", porque:"Es la excepción: con metales el hidrógeno queda negativo, porque el metal atrae menos que él."},
      {texto:"0", porque:"Cero solo cuando está solo, como H₂."},
      {texto:"−2", porque:"El hidrógeno solo tiene un electrón: no puede ser −2."}],
    porque:"El hidrógeno es +1 con no metales, pero −1 con metales. Los hidruros metálicos son esa excepción." },

  { id:"form-03", tema:"fyq-formulacion-inorganica", etiqueta:"Suma cero",
    enunciado:"En el SO₃, ¿con qué número de oxidación actúa el azufre?",
    opciones:[{texto:"+6", bien:true},
      {texto:"+3", porque:"Has contado un oxígeno por cada unidad. Son tres oxígenos a −2: −6 en total."},
      {texto:"−6", porque:"El signo va al revés: el oxígeno es el negativo, así que el azufre es positivo."},
      {texto:"+2", porque:"Con +2 la suma daría −4, no cero."}],
    porque:"Tres oxígenos son −6, y el compuesto es neutro: el azufre tiene que ser +6." },

  { id:"form-04", tema:"fyq-formulacion-inorganica", etiqueta:"Óxidos",
    enunciado:"La fórmula del óxido de aluminio es…",
    opciones:[{texto:"Al₂O₃", bien:true},
      {texto:"AlO", porque:"No cuadra: el aluminio es +3 y el oxígeno −2, así que no se cancelan uno a uno."},
      {texto:"Al₃O₂", porque:"Está cruzado al revés: el 3 va al oxígeno y el 2 al aluminio."},
      {texto:"AlO₃", porque:"Un aluminio (+3) con tres oxígenos (−6) deja carga sobrante."}],
    porque:"Al³⁺ y O²⁻: se cruzan y quedan dos aluminios y tres oxígenos. +6 y −6 se cancelan." },

  { id:"form-05", tema:"fyq-formulacion-inorganica", etiqueta:"Prefijos",
    enunciado:"¿Cómo se lee Fe₂O₃ en nomenclatura de composición?",
    opciones:[{texto:"Trióxido de dihierro", bien:true},
      {texto:"Óxido de hierro(II)", porque:"Ese sería el FeO. Aquí el hierro actúa con +3."},
      {texto:"Dióxido de trihierro", porque:"Los prefijos están cambiados: hay tres oxígenos y dos hierros."},
      {texto:"Óxido férrico doble", porque:"«Doble» no existe en ninguna nomenclatura."}],
    porque:"Se lee de derecha a izquierda con los prefijos: tri-óxido de di-hierro. En stock sería óxido de hierro(III)." },

  { id:"form-06", tema:"fyq-formulacion-inorganica", etiqueta:"Hidróxidos",
    enunciado:"¿Cuál es la fórmula del hidróxido de calcio?",
    opciones:[{texto:"Ca(OH)₂", bien:true},
      {texto:"CaOH", porque:"El calcio es +2 y el grupo OH es −1: hacen falta dos OH."},
      {texto:"CaOH₂", porque:"Sin paréntesis, el 2 afectaría solo al hidrógeno. Hay que agrupar: (OH)₂."},
      {texto:"Ca₂OH", porque:"Está al revés: el 2 va en el OH."}],
    porque:"El grupo OH vale −1 y va entre paréntesis cuando hay más de uno, para que el subíndice afecte al grupo entero." },

  { id:"form-07", tema:"fyq-formulacion-inorganica", etiqueta:"Paréntesis",
    enunciado:"¿Por qué se escribe Mg(OH)₂ y no MgOH₂?",
    opciones:[{texto:"Para que el 2 multiplique a todo el grupo OH", bien:true},
      {texto:"Por costumbre", porque:"No es estética: sin paréntesis la fórmula significa otra cosa."},
      {texto:"Para que quede más claro visualmente", porque:"Cambia el significado, no solo la claridad."},
      {texto:"Porque el magnesio lleva siempre paréntesis", porque:"El paréntesis depende del grupo repetido, no del metal."}],
    porque:"MgOH₂ diría un oxígeno y dos hidrógenos. Mg(OH)₂ dice dos grupos OH completos: dos oxígenos y dos hidrógenos." },

  { id:"form-08", tema:"fyq-formulacion-inorganica", etiqueta:"Hidrácidos",
    enunciado:"El HCl disuelto en agua se llama…",
    opciones:[{texto:"Ácido clorhídrico", bien:true},
      {texto:"Cloruro de hidrógeno", porque:"Así se llama el gas puro. Disuelto en agua cambia de nombre."},
      {texto:"Ácido clórico", porque:"Ese es otro compuesto, el HClO₃, que además lleva oxígeno."},
      {texto:"Hidruro de cloro", porque:"Los hidruros llevan el hidrógeno detrás y van con metales."}],
    porque:"El mismo compuesto tiene dos nombres: cloruro de hidrógeno en estado puro, ácido clorhídrico en disolución." },

  { id:"form-09", tema:"fyq-formulacion-inorganica", etiqueta:"Sales",
    enunciado:"La fórmula del sulfuro de aluminio es…",
    opciones:[{texto:"Al₂S₃", bien:true},
      {texto:"AlS", porque:"No cuadra: +3 y −2 no se cancelan uno a uno."},
      {texto:"Al₃S₂", porque:"Cruzado al revés."},
      {texto:"AlS₃", porque:"Un aluminio con tres azufres deja carga sobrante."}],
    porque:"Al³⁺ con S²⁻: se cruzan y salen dos aluminios y tres azufres, igual que en el óxido." },

  { id:"form-10", tema:"fyq-formulacion-inorganica", etiqueta:"Clasificar",
    enunciado:"¿Qué tipo de compuesto es el KOH?",
    opciones:[{texto:"Un hidróxido", bien:true},
      {texto:"Un óxido", porque:"Lleva oxígeno, sí, pero junto al hidrógeno formando el grupo OH."},
      {texto:"Un hidruro", porque:"En un hidruro el hidrógeno va solo con el metal, sin oxígeno."},
      {texto:"Una sal", porque:"Las sales binarias no llevan oxígeno ni hidrógeno."}],
    porque:"Si ves el grupo OH junto a un metal, es un hidróxido. Son las bases típicas." },

  { id:"form-11", tema:"fyq-formulacion-inorganica", etiqueta:"Nombres propios",
    enunciado:"¿Cuál de estos compuestos tiene nombre propio aceptado?",
    opciones:[{texto:"NH₃, que se llama amoniaco", bien:true},
      {texto:"CaO", porque:"Se llama óxido de calcio: nombre normal, sin excepción."},
      {texto:"NaCl", porque:"Cloruro de sodio. «Sal» es el nombre común, no el químico."},
      {texto:"SO₂", porque:"Dióxido de azufre, siguiendo las reglas."}],
    porque:"El amoniaco (NH₃), el agua (H₂O) y el metano (CH₄) conservan su nombre tradicional aunque no siga las reglas." },

  { id:"form-12", tema:"fyq-formulacion-inorganica", etiqueta:"Método",
    enunciado:"Para formular a partir del nombre, lo primero es…",
    opciones:[{texto:"Saber los números de oxidación de cada elemento", bien:true},
      {texto:"Contar las letras", porque:"Eso no dice nada del compuesto."},
      {texto:"Mirar cuál va primero en el abecedario", porque:"El orden lo marca la química, no el alfabeto."},
      {texto:"Buscar el prefijo", porque:"Ayuda cuando lo hay, pero muchos nombres no lo llevan."}],
    porque:"Sin las valencias no se puede cruzar nada. Por eso hay que llevarlas sabidas: es la tabla que de verdad hay que memorizar." },

  { id:"form-13", tema:"fyq-formulacion-inorganica", etiqueta:"Comprobación",
    enunciado:"Escribes una fórmula y quieres comprobarla. ¿Qué haces?",
    opciones:[{texto:"Sumar todos los números de oxidación: tiene que dar cero", bien:true},
      {texto:"Contar que haya el mismo número de átomos de cada uno", porque:"No tienen por qué ser iguales: en el CO₂ hay uno y dos."},
      {texto:"Ver que el metal vaya primero", porque:"Eso es cierto pero no comprueba si los subíndices están bien."},
      {texto:"Mirar si suena bien", porque:"La química no se comprueba de oído."}],
    porque:"Un compuesto neutro suma cero. Si no da cero, los subíndices están mal." },

  { id:"form-14", tema:"fyq-formulacion-inorganica", etiqueta:"Problema",
    enunciado:"El hierro forma dos óxidos: FeO y Fe₂O₃. ¿Por qué?",
    opciones:[{texto:"Porque el hierro puede actuar con +2 o con +3", bien:true},
      {texto:"Porque el oxígeno cambia de valencia", porque:"El oxígeno es fijo en −2: el que cambia es el hierro."},
      {texto:"Porque uno está mal escrito", porque:"Los dos existen y son compuestos distintos."},
      {texto:"Porque depende de la temperatura", porque:"La temperatura influye en cuál se forma, pero la razón química es la valencia."}],
    porque:"Los metales de transición tienen varias valencias. Por eso hace falta indicarlo: óxido de hierro(II) y óxido de hierro(III)." }
);
