/* preguntas-tec.js — banco de Tecnología y Digitalización. */
BANCO.push(
  { id:"tec-01", tema:"tec-programacion", etiqueta:"Variables",
    enunciado:"¿Qué vale x después de: <code>x = 5</code> y luego <code>x = x + 3</code>?",
    opciones:[{texto:"8", bien:true},
      {texto:"5", porque:"La segunda línea sí cambia el valor: lo machaca con el resultado."},
      {texto:"53", porque:"Eso sería juntar textos. Con números, el + suma."},
      {texto:"Da error, porque x no puede estar en los dos lados", porque:"Sí puede: primero se calcula la derecha y luego se guarda en la izquierda."}],
    porque:"El = no significa «igual»: significa «guarda esto aquí». Se calcula 5+3 y el resultado se mete en x." },

  { id:"tec-02", tema:"tec-programacion", etiqueta:"Bucles",
    enunciado:"¿Cuántas veces se repite <code>for i in range(4):</code>?",
    opciones:[{texto:"4 veces", bien:true},
      {texto:"5 veces", porque:"Empieza en 0 y acaba en 3: son cuatro valores, no cinco."},
      {texto:"3 veces", porque:"Cuenta el 0: 0, 1, 2, 3 son cuatro."},
      {texto:"Infinitas", porque:"El bucle for tiene un final marcado; el que se puede quedar colgado es el while."}],
    porque:"range(4) da 0, 1, 2 y 3: cuatro vueltas. Empieza en 0 y no llega al 4." },

  { id:"tec-03", tema:"tec-programacion", etiqueta:"Bucles",
    enunciado:"<code>range(2, 7)</code> genera…",
    opciones:[{texto:"2, 3, 4, 5, 6", bien:true},
      {texto:"2, 3, 4, 5, 6, 7", porque:"El segundo número nunca se alcanza: es el tope, no el último."},
      {texto:"0, 1, 2, 3, 4, 5, 6, 7", porque:"Con dos números, el primero es donde empieza."},
      {texto:"2 y 7", porque:"No son los extremos: es toda la cuenta entre ellos."}],
    porque:"Incluye el primero y excluye el último. Es la trampa que más se falla." },

  { id:"tec-04", tema:"tec-programacion", etiqueta:"Condicionales",
    enunciado:"¿Cuál es la diferencia entre <code>=</code> y <code>==</code>?",
    opciones:[{texto:"Uno asigna un valor y el otro compara", bien:true},
      {texto:"Son lo mismo", porque:"No: confundirlos es de los errores más frecuentes al empezar."},
      {texto:"== solo vale para números", porque:"También compara textos: <code>nombre == \"Ana\"</code>."},
      {texto:"= es más rápido", porque:"Hacen cosas distintas: no se pueden comparar en velocidad."}],
    porque:"<code>x = 5</code> guarda un 5 en x. <code>x == 5</code> pregunta si x vale 5, y responde verdadero o falso." },

  { id:"tec-05", tema:"tec-programacion", etiqueta:"Tipos",
    enunciado:"<code>\"5\" + 3</code> en Python…",
    opciones:[{texto:"Da error: no se puede sumar texto y número", bien:true},
      {texto:"Da 8", porque:"Python no convierte solo: «5» con comillas es texto."},
      {texto:"Da \"53\"", porque:"Eso pasaría con <code>\"5\" + \"3\"</code>, los dos texto."},
      {texto:"Da 53", porque:"No hay forma de que salga ese número."}],
    porque:"Lo que va entre comillas es texto. Para sumarlo hay que convertirlo: <code>int(\"5\") + 3</code>." },

  { id:"tec-06", tema:"tec-programacion", etiqueta:"Sangría",
    enunciado:"¿Para qué sirve la sangría (indentación) en Python?",
    opciones:[{texto:"Para marcar qué instrucciones están dentro de un bloque", bien:true},
      {texto:"Solo para que quede bonito", porque:"En otros lenguajes sí es estética; en Python cambia lo que hace el programa."},
      {texto:"Para separar variables", porque:"Las variables no necesitan sangría."},
      {texto:"Es opcional", porque:"No lo es: sin ella, Python da error."}],
    porque:"Python usa los espacios en vez de llaves. Lo indentado está dentro del if o del bucle; lo que no, está fuera." },

  { id:"tec-07", tema:"tec-programacion", etiqueta:"While",
    enunciado:"¿Qué pasa si en un <code>while</code> se olvida cambiar la variable de la condición?",
    opciones:[{texto:"Se queda repitiendo para siempre", bien:true},
      {texto:"Da error al escribirlo", porque:"El código es correcto: el problema aparece al ejecutarlo."},
      {texto:"Se ejecuta una vez", porque:"Se ejecuta infinitas: la condición nunca deja de cumplirse."},
      {texto:"No se ejecuta nunca", porque:"Si la condición es cierta al principio, entra y no sale."}],
    porque:"Bucle infinito: el error más típico con while. Siempre hay que asegurarse de que algo acerque la condición al final." },

  { id:"tec-08", tema:"tec-programacion", etiqueta:"Funciones",
    enunciado:"¿Para qué sirve una función?",
    opciones:[{texto:"Para reutilizar un trozo de código con distintos datos", bien:true},
      {texto:"Para que el programa vaya más rápido", porque:"No es cuestión de velocidad, sino de organización y reutilización."},
      {texto:"Para guardar valores", porque:"Eso son las variables."},
      {texto:"Para dibujar en pantalla", porque:"Eso dependerá de lo que haga la función, no de que sea función."}],
    porque:"Escribes el código una vez y lo llamas cuantas veces quieras, con datos distintos. Si hay que cambiarlo, se cambia en un sitio." },

  { id:"tec-09", tema:"tec-programacion", etiqueta:"Listas",
    enunciado:"En <code>lista = [10, 20, 30]</code>, ¿qué devuelve <code>lista[0]</code>?",
    opciones:[{texto:"10", bien:true},
      {texto:"20", porque:"Ese sería lista[1]: la cuenta empieza en 0."},
      {texto:"0", porque:"El 0 es la posición, no el valor que hay en ella."},
      {texto:"Da error", porque:"La posición 0 siempre existe si la lista no está vacía."}],
    porque:"Las listas empiezan a contar en 0: el primer elemento es lista[0]." },

  { id:"tec-10", tema:"tec-programacion", etiqueta:"Depurar",
    enunciado:"Tu programa falla. ¿Qué es lo primero que hay que hacer?",
    opciones:[{texto:"Leer el mensaje de error, que dice la línea", bien:true},
      {texto:"Reescribirlo entero", porque:"Casi nunca hace falta: el error suele estar en una línea concreta."},
      {texto:"Probar a cambiar cosas al azar", porque:"Así se arreglan unas cosas y se rompen otras sin saber por qué."},
      {texto:"Preguntar sin mirarlo", porque:"El mensaje suele decir exactamente qué pasa y dónde."}],
    porque:"El mensaje de error dice el tipo de fallo y la línea. Leerlo ahorra más tiempo que cualquier otra cosa." },

  { id:"tec-11", tema:"tec-electronica", etiqueta:"Ley de Ohm",
    enunciado:"Con V = 12 V y R = 4 Ω, la intensidad es…",
    opciones:[{texto:"3 A", bien:true},
      {texto:"48 A", porque:"Has multiplicado. La intensidad se despeja dividiendo: I = V/R."},
      {texto:"0,33 A", porque:"Has dividido al revés: R entre V."},
      {texto:"8 A", porque:"Has restado."}],
    porque:"I = V / R = 12 / 4 = 3 A." },

  { id:"tec-12", tema:"tec-electronica", etiqueta:"Circuitos",
    enunciado:"En un circuito en SERIE, si se funde una bombilla…",
    opciones:[{texto:"Se apagan todas", bien:true},
      {texto:"Las demás siguen encendidas", porque:"Eso pasa en paralelo, donde cada rama es independiente."},
      {texto:"Las demás lucen más", porque:"No hay circuito: al cortarse, no pasa corriente por ninguna."},
      {texto:"Depende de cuál se funda", porque:"En serie da igual cuál: la corriente tiene un único camino."}],
    porque:"En serie hay un solo camino para la corriente. Si se corta en un punto, se corta para todos." },

  { id:"tec-13", tema:"tec-electronica", etiqueta:"Circuitos",
    enunciado:"Dos resistencias de 10 Ω en PARALELO equivalen a…",
    opciones:[{texto:"5 Ω", bien:true},
      {texto:"20 Ω", porque:"Eso sería en serie, donde se suman."},
      {texto:"10 Ω", porque:"En paralelo la resistencia total siempre baja: hay más caminos para la corriente."},
      {texto:"100 Ω", porque:"Has multiplicado sin dividir por la suma."}],
    porque:"En paralelo, dos resistencias iguales dan la mitad. Más caminos, menos resistencia total." },

  { id:"tec-14", tema:"tec-electronica", etiqueta:"Potencia",
    enunciado:"Un aparato de 2.000 W encendido 3 horas consume…",
    opciones:[{texto:"6 kWh", bien:true},
      {texto:"6.000 kWh", porque:"Te has dejado el paso de vatios a kilovatios: 2.000 W son 2 kW."},
      {texto:"2 kWh", porque:"Falta multiplicar por las horas."},
      {texto:"666 W", porque:"Has dividido. El consumo es potencia por tiempo."}],
    porque:"Energía = potencia × tiempo = 2 kW × 3 h = 6 kWh. Así es como te cobra la factura de la luz." }
);
