/* preguntas-fyq2.js — banco del enlace químico. */
BANCO.push(
  { id:"enl-01", tema:"fyq-enlace", etiqueta:"Por qué se unen",
    enunciado:"¿Por qué se unen los átomos?",
    opciones:[{texto:"Para conseguir la última capa completa", bien:true},
      {texto:"Porque se atraen por la gravedad", porque:"La gravedad entre átomos es despreciable: lo que manda son las cargas eléctricas."},
      {texto:"Para ganar masa", porque:"Los enlaces no cambian la masa: reordenan electrones."},
      {texto:"Porque los empuja el calor", porque:"El calor más bien rompe enlaces que los forma."}],
    porque:"Un átomo con la capa llena es estable y no necesita nada. Los demás se unen para conseguirlo, ganando, cediendo o compartiendo electrones." },

  { id:"enl-02", tema:"fyq-enlace", etiqueta:"Iónico",
    enunciado:"El enlace iónico se forma entre…",
    opciones:[{texto:"Un metal y un no metal", bien:true},
      {texto:"Dos no metales", porque:"Los dos quieren coger electrones y ninguno cede: acaban compartiéndolos, que es covalente."},
      {texto:"Dos metales", porque:"Eso es enlace metálico: los electrones quedan en una nube común."},
      {texto:"Dos gases nobles", porque:"Los gases nobles ya están completos: no forman enlaces."}],
    porque:"El metal suelta electrones y el no metal los coge. Quedan iones de signo contrario que se atraen." },

  { id:"enl-03", tema:"fyq-enlace", etiqueta:"Iónico",
    enunciado:"En el NaCl, ¿qué ha pasado con el electrón del sodio?",
    opciones:[{texto:"Ha pasado al cloro, y ahora hay Na⁺ y Cl⁻", bien:true},
      {texto:"Se comparte entre los dos", porque:"Eso es el enlace covalente. En el iónico el electrón se transfiere del todo."},
      {texto:"Se ha perdido", porque:"No se pierde: lo tiene el cloro."},
      {texto:"Da vueltas alrededor de los dos", porque:"Esa imagen no corresponde a ningún enlace real."}],
    porque:"Al sodio le sobraba uno y al cloro le faltaba uno: transferencia limpia, y los iones resultantes se atraen." },

  { id:"enl-04", tema:"fyq-enlace", etiqueta:"Covalente",
    enunciado:"En la molécula de agua (H₂O), el enlace es…",
    opciones:[{texto:"Covalente: comparten electrones", bien:true},
      {texto:"Iónico", porque:"Hidrógeno y oxígeno son los dos no metales: ninguno cede del todo."},
      {texto:"Metálico", porque:"No hay ningún metal en el agua."},
      {texto:"No hay enlace, es una mezcla", porque:"El agua es un compuesto, no una mezcla: los átomos están unidos."}],
    porque:"Dos no metales comparten pares de electrones. El oxígeno comparte uno con cada hidrógeno." },

  { id:"enl-05", tema:"fyq-enlace", etiqueta:"Metálico",
    enunciado:"¿Por qué los metales conducen la electricidad en estado sólido?",
    opciones:[{texto:"Porque tienen electrones libres moviéndose", bien:true},
      {texto:"Porque son duros", porque:"El diamante es durísimo y no conduce."},
      {texto:"Porque tienen muchos protones", porque:"Los protones están fijos en el núcleo: no se mueven."},
      {texto:"Porque brillan", porque:"El brillo es otra consecuencia de lo mismo, no la causa."}],
    porque:"En el enlace metálico los electrones de valencia quedan sueltos en una nube común: pueden circular, y eso es la corriente." },

  { id:"enl-06", tema:"fyq-enlace", etiqueta:"Propiedades",
    enunciado:"La sal conduce la electricidad disuelta en agua, pero no en estado sólido. ¿Por qué?",
    opciones:[{texto:"Porque los iones solo quedan libres al disolverse", bien:true},
      {texto:"Porque el agua conduce por sí sola", porque:"El agua pura conduce muy poco: lo que conduce son los iones disueltos."},
      {texto:"Porque al disolverse se convierte en metal", porque:"Sigue siendo la misma sustancia; solo cambia la libertad de los iones."},
      {texto:"Porque el agua rompe los átomos", porque:"Los átomos no se rompen: se separan los iones que ya existían."}],
    porque:"En el cristal los iones están fijos en su sitio. En agua se separan y pueden moverse, y las cargas en movimiento son corriente." },

  { id:"enl-07", tema:"fyq-enlace", etiqueta:"Propiedades",
    enunciado:"¿Por qué los compuestos iónicos tienen puntos de fusión tan altos?",
    opciones:[{texto:"Porque la atracción entre iones es muy fuerte", bien:true},
      {texto:"Porque pesan mucho", porque:"La masa no determina el punto de fusión: el mercurio pesa mucho y es líquido."},
      {texto:"Porque son duros", porque:"La dureza es otra consecuencia de lo mismo, no la causa."},
      {texto:"Porque no tienen electrones", porque:"Sí los tienen: están todos colocados."}],
    porque:"Hay que vencer la atracción de toda una red de cargas. La sal funde por encima de 800 °C." },

  { id:"enl-08", tema:"fyq-enlace", etiqueta:"Propiedades",
    enunciado:"Una sustancia es gas a temperatura ambiente y no conduce. Su enlace es…",
    opciones:[{texto:"Covalente", bien:true},
      {texto:"Iónico", porque:"Los iónicos son sólidos con puntos de fusión altísimos: nunca gases a temperatura ambiente."},
      {texto:"Metálico", porque:"Los metales son sólidos (salvo el mercurio) y además conducen."},
      {texto:"No tiene enlace", porque:"Si es una sustancia compuesta, sus átomos están unidos de alguna forma."}],
    porque:"Moléculas covalentes separadas: se sueltan con poca energía y no hay cargas libres para conducir." },

  { id:"enl-09", tema:"fyq-enlace", etiqueta:"Octeto",
    enunciado:"El magnesio (Z = 12) forma el ion…",
    opciones:[{texto:"Mg²⁺", bien:true},
      {texto:"Mg²⁻", porque:"Los metales sueltan electrones, no los cogen: quedan positivos."},
      {texto:"Mg⁺", porque:"Tiene 2 electrones en la última capa, así que suelta los dos."},
      {texto:"Mg⁶⁻", porque:"Coger seis le costaría muchísimo más que soltar dos."}],
    porque:"Su configuración acaba en 3s²: soltando esos dos se queda como el neón, con la capa llena." },

  { id:"enl-10", tema:"fyq-enlace", etiqueta:"Fórmulas",
    enunciado:"¿Cuál es la fórmula del compuesto entre Ca²⁺ y Cl⁻?",
    opciones:[{texto:"CaCl₂", bien:true},
      {texto:"CaCl", porque:"No cuadran las cargas: sobraría una carga positiva."},
      {texto:"Ca₂Cl", porque:"Está al revés: hacen falta dos cloros, no dos calcios."},
      {texto:"Ca₂Cl₂", porque:"Se puede simplificar, y además no equilibra."}],
    porque:"Cada calcio aporta +2, así que hacen falta dos cloros de −1 para que la suma sea cero." },

  { id:"enl-11", tema:"fyq-enlace", etiqueta:"Covalente",
    enunciado:"En el O₂ los átomos comparten…",
    opciones:[{texto:"Dos pares de electrones (enlace doble)", bien:true},
      {texto:"Un par", porque:"Con uno solo, cada oxígeno se quedaría en 7 electrones: no llega al octeto."},
      {texto:"Tres pares", porque:"Eso es el nitrógeno N₂, al que le faltan tres."},
      {texto:"Ninguno: se transfieren", porque:"Entre dos átomos iguales no hay transferencia: no hay razón para que uno ceda."}],
    porque:"Al oxígeno le faltan 2 electrones, así que comparte dos pares con el otro oxígeno: un doble enlace." },

  { id:"enl-12", tema:"fyq-enlace", etiqueta:"Metálico",
    enunciado:"¿Por qué un metal se puede estirar en hilos sin romperse?",
    opciones:[{texto:"Porque los átomos pueden deslizarse sin perder la unión", bien:true},
      {texto:"Porque es blando", porque:"El acero no es blando y también se lamina."},
      {texto:"Porque tiene enlaces débiles", porque:"El enlace metálico es fuerte: por eso funden a temperaturas altas."},
      {texto:"Porque tiene agua dentro", porque:"No hay agua en un metal."}],
    porque:"La nube de electrones sigue envolviendo a los núcleos aunque estos cambien de posición. En un cristal iónico, ese mismo desplazamiento enfrenta cargas iguales y lo parte." },

  { id:"enl-13", tema:"fyq-enlace", etiqueta:"Agua",
    enunciado:"¿Por qué el agua disuelve tan bien la sal?",
    opciones:[{texto:"Porque sus moléculas tienen polos y rodean a los iones", bien:true},
      {texto:"Porque el agua es un buen conductor", porque:"El agua pura conduce muy poco: es al revés, conduce porque disuelve iones."},
      {texto:"Porque la sal se derrite", porque:"Derretirse es por calor: aquí no hay fusión, hay disolución."},
      {texto:"Porque reacciona químicamente con la sal", porque:"No hay reacción: los iones se separan y siguen siendo los mismos."}],
    porque:"La molécula de agua tiene una parte algo negativa y otra algo positiva. Rodea cada ion por el lado que le atrae y lo separa de la red." },

  { id:"enl-14", tema:"fyq-enlace", etiqueta:"Problema",
    enunciado:"Una sustancia funde a 1.200 °C, es dura, frágil y conduce disuelta. ¿Qué es?",
    opciones:[{texto:"Un compuesto iónico", bien:true},
      {texto:"Un metal", porque:"Un metal conduciría también en sólido, y no sería frágil sino maleable."},
      {texto:"Una sustancia covalente molecular", porque:"Esas funden a temperaturas bajas y no conducen ni disueltas."},
      {texto:"Un gas noble", porque:"Los gases nobles no forman sólidos a temperatura ambiente ni conducen."}],
    porque:"Las cuatro pistas coinciden: red de iones, fuerte pero quebradiza, y con cargas que solo se liberan al disolverse." }
);
