/* preguntas-cin.js — banco de cinemática. */
BANCO.push(
  { id:"cin-01", tema:"fyq-cinematica", etiqueta:"Referencia",
    enunciado:"Vas sentado en un tren en marcha. ¿Estás en movimiento?",
    opciones:[{texto:"Depende del sistema de referencia", bien:true},
      {texto:"Sí, siempre", porque:"Respecto al asiento de al lado no te mueves nada. Sin decir respecto a qué, la pregunta no tiene respuesta."},
      {texto:"No, porque estás sentado", porque:"Respecto a las vías te mueves a la velocidad del tren."},
      {texto:"Solo si el tren acelera", porque:"A velocidad constante también te mueves respecto a la estación."}],
    porque:"El movimiento siempre es relativo a algo. Respecto al tren estás quieto; respecto a la vía, no." },

  { id:"cin-02", tema:"fyq-cinematica", etiqueta:"Trayectoria",
    enunciado:"Das una vuelta completa a una pista de 400 m y vuelves a la salida. ¿Cuál es tu desplazamiento?",
    opciones:[{texto:"0 m", bien:true},
      {texto:"400 m", porque:"400 m es la distancia recorrida, la longitud de la trayectoria. El desplazamiento solo mira de dónde sales y dónde acabas."},
      {texto:"200 m", porque:"No hay ningún motivo para dividir entre dos."},
      {texto:"No se puede saber", porque:"Se sabe: sales y llegas al mismo punto."}],
    porque:"Distancia recorrida = 400 m. Desplazamiento = posición final − inicial = 0." },

  { id:"cin-03", tema:"fyq-cinematica", etiqueta:"Unidades",
    enunciado:"¿Cuánto son 72 km/h en m/s?",
    opciones:[{texto:"20 m/s", bien:true},
      {texto:"259,2 m/s", porque:"Has multiplicado por 3,6. Eso es para pasar de m/s a km/h, al revés."},
      {texto:"72 m/s", porque:"Las unidades no son intercambiables: un m/s es mucho más que un km/h."},
      {texto:"7,2 m/s", porque:"Se divide entre 3,6, no entre 10."}],
    porque:"De km/h a m/s se divide entre 3,6: 72 / 3,6 = 20 m/s." },

  { id:"cin-04", tema:"fyq-cinematica", etiqueta:"MRU",
    enunciado:"En un MRU, ¿qué pasa con la velocidad?",
    opciones:[{texto:"Es constante", bien:true},
      {texto:"Aumenta de forma constante", porque:"Eso es el MRUA: lo que es constante ahí es la aceleración."},
      {texto:"Es cero", porque:"Si fuera cero no habría movimiento."},
      {texto:"Depende de la distancia", porque:"En el MRU la velocidad no cambia, recorras lo que recorras."}],
    porque:"MRU = movimiento rectilíneo uniforme: misma velocidad todo el rato y, por tanto, aceleración cero." },

  { id:"cin-05", tema:"fyq-cinematica", etiqueta:"Gráficas",
    enunciado:"En una gráfica posición–tiempo (x–t), una línea recta inclinada significa…",
    opciones:[{texto:"Velocidad constante", bien:true},
      {texto:"Aceleración constante", porque:"Con aceleración, la x–t es una curva (parábola). Es la v–t la que sale recta."},
      {texto:"Que está parado", porque:"Parado sería una línea horizontal: la posición no cambia."},
      {texto:"Que va cuesta arriba", porque:"La gráfica no dibuja el camino: dibuja la posición frente al tiempo."}],
    porque:"En x–t, la pendiente es la velocidad. Pendiente constante → velocidad constante." },

  { id:"cin-06", tema:"fyq-cinematica", etiqueta:"Gráficas",
    enunciado:"En una gráfica velocidad–tiempo (v–t), ¿qué representa el área bajo la línea?",
    opciones:[{texto:"La distancia recorrida", bien:true},
      {texto:"La aceleración", porque:"La aceleración es la pendiente de la v–t, no el área."},
      {texto:"La velocidad media", porque:"El área tiene unidades de (m/s)·s = m: es una distancia."},
      {texto:"El tiempo", porque:"El tiempo ya está en el eje horizontal."}],
    porque:"Velocidad × tiempo = distancia. Por eso el área bajo la v–t son metros." },

  { id:"cin-07", tema:"fyq-cinematica", etiqueta:"MRUA",
    enunciado:"Un coche parte del reposo y acelera a 3 m/s². ¿Qué velocidad lleva a los 5 s?",
    opciones:[{texto:"15 m/s", bien:true},
      {texto:"37,5 m/s", porque:"Has calculado ½·a·t², que es la distancia, no la velocidad."},
      {texto:"8 m/s", porque:"Has sumado aceleración y tiempo. Se multiplican: v = v₀ + a·t."},
      {texto:"0,6 m/s", porque:"Has dividido 3 entre 5."}],
    porque:"v = v₀ + a·t = 0 + 3·5 = 15 m/s." },

  { id:"cin-08", tema:"fyq-cinematica", etiqueta:"MRUA",
    enunciado:"Un coche frena. ¿Qué signo tiene la aceleración si la velocidad es positiva?",
    opciones:[{texto:"Negativa", bien:true},
      {texto:"Positiva", porque:"Si fuera positiva, la velocidad aumentaría: iría más rápido, no frenaría."},
      {texto:"Cero", porque:"Con aceleración cero la velocidad no cambia: no podría frenar."},
      {texto:"Depende de la masa", porque:"El signo lo decide si la velocidad sube o baja, no la masa."}],
    porque:"Frenar es que la velocidad disminuya. Si la velocidad es positiva, eso exige una aceleración de signo contrario." },

  { id:"cin-09", tema:"fyq-cinematica", etiqueta:"Caída libre",
    enunciado:"Sin aire, sueltas a la vez una bola de acero y una canica desde la misma altura. ¿Cuál llega antes?",
    opciones:[{texto:"Llegan a la vez", bien:true},
      {texto:"La de acero, porque pesa más", porque:"Es lo que parece, pero sin rozamiento del aire todas caen con la misma aceleración, g. Lo comprobaron en la Luna con un martillo y una pluma."},
      {texto:"La canica, porque es más pequeña", porque:"El tamaño solo importa por el aire, y aquí no hay aire."},
      {texto:"Depende de la altura", porque:"Desde cualquier altura, sin aire, llegan juntas."}],
    porque:"En caída libre la aceleración es g = 9,8 m/s² para todo, pese lo que pese. Si en la vida real la pluma cae más lenta, es por el aire." },

  { id:"cin-10", tema:"fyq-cinematica", etiqueta:"Caída libre",
    enunciado:"Lanzas una pelota hacia arriba. En el punto más alto, ¿cuánto vale su velocidad?",
    opciones:[{texto:"0 m/s, y la aceleración sigue siendo g", bien:true},
      {texto:"0 m/s, y la aceleración también es 0", porque:"Si la aceleración fuera 0 ahí, la pelota se quedaría flotando. La gravedad no se apaga nunca."},
      {texto:"La misma con la que salió", porque:"Sube cada vez más lenta hasta pararse; la recupera al volver abajo."},
      {texto:"Es máxima", porque:"Arriba es justo donde va más lenta."}],
    porque:"Arriba la velocidad es cero un instante, pero la gravedad sigue tirando: por eso vuelve a bajar." },

  { id:"cin-11", tema:"fyq-cinematica", etiqueta:"Circular",
    enunciado:"Un coche da vueltas a una rotonda a 30 km/h constantes. ¿Tiene aceleración?",
    opciones:[{texto:"Sí, porque cambia la dirección de la velocidad", bien:true},
      {texto:"No, porque la rapidez es constante", porque:"La velocidad tiene dirección, y en una curva cambia a cada instante. Cambiar de dirección también es acelerar."},
      {texto:"Solo si frena", porque:"Frenar es una forma de acelerar, pero no la única."},
      {texto:"Solo si la rotonda es grande", porque:"Pasa en cualquier curva; si es cerrada, incluso más."}],
    porque:"En el MCU hay aceleración centrípeta, hacia el centro. Es la que notas que te empuja hacia fuera de la curva." },

  { id:"cin-12", tema:"fyq-cinematica", etiqueta:"Circular",
    enunciado:"Una noria da una vuelta cada 20 s. ¿Cuál es su frecuencia?",
    opciones:[{texto:"0,05 Hz", bien:true},
      {texto:"20 Hz", porque:"20 s es el periodo. La frecuencia es la inversa: vueltas por segundo."},
      {texto:"2π/20 Hz", porque:"Eso es la velocidad angular en rad/s, no la frecuencia."},
      {texto:"0,5 Hz", porque:"1 / 20 = 0,05, no 0,5."}],
    porque:"Frecuencia = 1 / periodo = 1 / 20 = 0,05 vueltas por segundo (Hz)." },

  { id:"cin-13", tema:"fyq-cinematica", etiqueta:"MRUA",
    enunciado:"Si duplicas el tiempo que un objeto acelera partiendo del reposo, la distancia recorrida…",
    opciones:[{texto:"Se multiplica por 4", bien:true},
      {texto:"Se duplica", porque:"Eso pasaría en un MRU. En el MRUA, Δx = ½·a·t²: el tiempo va al cuadrado."},
      {texto:"Se queda igual", porque:"Más tiempo acelerando siempre es más distancia."},
      {texto:"Se reduce a la mitad", porque:"Irá más lejos, no menos."}],
    porque:"Δx = ½·a·t². Con 2t: ½·a·(2t)² = 4·(½·a·t²). Por eso la distancia de frenada crece tanto con la velocidad." },

  { id:"cin-14", tema:"fyq-cinematica", etiqueta:"Gráficas",
    enunciado:"En una gráfica v–t, una línea horizontal por encima del eje significa…",
    opciones:[{texto:"Que se mueve a velocidad constante", bien:true},
      {texto:"Que está parado", porque:"Parado sería v = 0: la línea iría pegada al eje. Aquí la velocidad vale algo, y no cambia."},
      {texto:"Que acelera", porque:"Para acelerar la línea tendría que subir o bajar."},
      {texto:"Que va hacia atrás", porque:"Por encima del eje la velocidad es positiva."}],
    porque:"En v–t, horizontal = la velocidad no cambia = MRU. Ojo: en la x–t, horizontal significa parado. Es el error que más se repite." }
);
