/* temas.js — la lista de temas del curso. Añadir un tema = una línea más aquí
   y una carpeta en temas/ copiada de plantilla/. Nada más. */
const TEMAS = [
  { id:"fyq-formulacion-inorganica", asignatura:"Física y Química", titulo:"Formulación inorgánica",
    resumen:"Números de oxidación, cruzar fórmulas, las cinco familias y las dos nomenclaturas. Puro entrenamiento.",
    estado:"listo" },
  { id:"fyq-enlace", asignatura:"Física y Química", titulo:"El enlace químico",
    resumen:"Iónico, covalente y metálico: por qué se unen los átomos y cómo reconocer cada enlace por las propiedades.",
    estado:"listo" },
  { id:"tec-programacion", asignatura:"Tecnología", titulo:"Programación",
    resumen:"Variables, condicionales, bucles, funciones y listas en Python, y cómo encontrar el fallo cuando algo no va.",
    estado:"listo" },
  { id:"ing-tenses", asignatura:"Inglés B2+", titulo:"Tiempos verbales",
    resumen:"Cuándo va cada tiempo, past simple contra present perfect, for y since, y los errores típicos de un español.",
    estado:"listo" },
  { id:"len-oracion-simple", asignatura:"Lengua", titulo:"Análisis sintáctico: la oración simple",
    resumen:"Sujeto y predicado, CD, CI, circunstanciales, atributo y suplemento, cada uno con su prueba.",
    estado:"listo" },
  { id:"mat-b-logaritmos", asignatura:"Matemáticas", titulo:"Logaritmos",
    resumen:"La potencia al revés: propiedades, cambio de base, ecuaciones exponenciales y las escalas de pH, decibelios y terremotos.",
    estado:"listo" },
  { id:"fyq-atomo", asignatura:"Física y Química", titulo:"Estructura atómica y sistema periódico",
    resumen:"Protones, neutrones y electrones; iones e isótopos; los modelos; y por qué la tabla está ordenada así.",
    estado:"listo" },
  { id:"mat-b-reales", asignatura:"Matemáticas", titulo:"Números reales e intervalos",
    resumen:"Qué tipo de número es cada cosa, fracción generatriz, intervalos, valor absoluto y errores.",
    estado:"listo" },
  { id:"mates-radicales", asignatura:"Matemáticas", titulo:"Radicales",
    resumen:"Qué es una raíz, cómo simplificarla, sumarlas, multiplicarlas y quitar raíces de los denominadores.",
    estado:"listo" },
  { id:"mates-funcion-cuadratica", asignatura:"Matemáticas", titulo:"La función cuadrática",
    resumen:"Qué hace cada número de $y=ax^2+bx+c$, dónde está el vértice y cuándo corta al eje X.",
    estado:"listo" },
  { id:"mates-sistemas", asignatura:"Matemáticas", titulo:"Sistemas de ecuaciones",
    resumen:"Sustitución, igualación y reducción, y qué significa que no haya solución.",
    estado:"en camino" },
  { id:"fyq-cinematica", asignatura:"Física y Química", titulo:"Cinemática",
    resumen:"MRU y MRUA: posición, velocidad y aceleración, y cómo se leen las gráficas.",
    estado:"en camino" },
];
